import "@/app/globals.css";

import type { Metadata } from "next";
import { Inter, Poppins } from "next/font/google";
import React from "react";
import { Providers } from "@/components/main-layout/providers";
import { EventListeners } from "@/components/main-layout/EventListeners";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Lang3s",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${inter.className} ${poppins.variable} min-h-[800] min-w-[800] antialiased`}
        style={{
          overflowAnchor: "none",
        }}
      >
        <Providers>
          <EventListeners>{children}</EventListeners>
        </Providers>
      </body>
    </html>
  );
}
