#!/usr/bin/env bash

if [ ! "$CONDA_DEFAULT_ENV" = "nlp" ]; then
  conda activate nlp
fi

if [ $# -eq 0 ]; then
  echo "Error: No argument provided."
  exit 1
fi

file=$1
shift

TRANSFORMERS_VERBOSITY=error
TOKENIZERS_PARALLELISM=false
PYTHONUNBUFFERED=1

export MODELS_DIR=./backend/nlp/models
python -m "backend.nlp.src.lang3s.$file" "$@"