#!/usr/bin/env bash

if [ $# -eq 0 ]; then
  echo "Error: No argument provided."
  exit 1
fi

file=$1
shift

export TRANSFORMERS_VERBOSITY=error
export TOKENIZERS_PARALLELISM=false
export PYTHONUNBUFFERED=1

export MODELS_DIR=./backend/nlp/models
uv run --project backend/nlp python -m "backend.nlp.src.lang3s.$file" "$@"