#!/usr/bin/env bash

if [ ! "$CONDA_DEFAULT_ENV" = "nlp" ]; then
  conda activate nlp
fi

if [ $# -eq 0 ]; then
  echo "Error: No argument provided."
  exit 1 # Exit with a non-zero status to indicate an error
fi

file=$1
shift

export MODELS_DIR=./backend/nlp/models
python -m "backend.nlp.src.lang3s.$file" $@