// This file is auto-generated by @hey-api/openapi-ts

import { type InfiniteData, infiniteQueryOptions, queryOptions, type UseMutationOptions } from '@tanstack/react-query';

import { client } from '../client.gen';
import { ApiClient, type Options } from '../sdk.gen';
import type { AddOntologyEntryData, AddOntologyEntryError, DeleteOntologyEntryData, DeleteOntologyEntryError, DocumentsGetAllData, DocumentsGetAllError, DocumentsGetAllResponse, EmbedEmbedPostData, EmbedEmbedPostError, JobsCreateJobData, JobsCreateJobError, JobsCreateJobResponse, JobsDeleteJobData, JobsDeleteJobError, JobsDeleteJobResponse, JobsGetJobData, JobsGetJobError, JobsGetJobResponse, JobsListJobsData, JobsListJobsError, JobsListJobsResponse, JobsUpdateJobData, JobsUpdateJobError, JobsUpdateJobResponse, MetadataCreateData, MetadataCreateError, MetadataDeleteData, MetadataDeleteError, MetadataDeleteResponse, MetadataGetBySourceData, MetadataGetBySourceError, MetadataGetBySourceResponse, MetadataProbeData, MetadataProbeError, MetadataProbeResponse, MetadataUpdateData, MetadataUpdateError, MetadataUpdateResponse, OntologyGetAnnotationsForDocumentData, OntologyGetAnnotationsForDocumentError, OntologyGetAnnotationsForDocumentResponse, OntologyGetData, OntologyGetError, OntologyGetNodePathData, OntologyGetNodePathError, OntologyGetNodePathResponse, OntologyGetPotentialMappingsData, OntologyGetPotentialMappingsError, OntologyGetPotentialMappingsResponse, OntologyGetResponse, OntologyNameExistsData, OntologyNameExistsError, OntologyNameExistsResponse, PrecomputedStatsGetByNameData, PrecomputedStatsGetByNameError, PrecomputedStatsGetByNameResponse, TopicsGetTopicData, TopicsGetTopicError, TopicsGetTopicResponse, UpdateOntologyEntryData, UpdateOntologyEntryError } from '../types.gen';

/**
 * Delete Job
 */
export const jobsDeleteJobMutation = (options?: Partial<Options<JobsDeleteJobData>>): UseMutationOptions<JobsDeleteJobResponse, JobsDeleteJobError, Options<JobsDeleteJobData>> => {
    const mutationOptions: UseMutationOptions<JobsDeleteJobResponse, JobsDeleteJobError, Options<JobsDeleteJobData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await ApiClient.__registry.get().jobsDeleteJob({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [params];
};

export const jobsGetJobQueryKey = (options: Options<JobsGetJobData>) => createQueryKey('jobsGetJob', options);

/**
 * Get Job
 */
export const jobsGetJobOptions = (options: Options<JobsGetJobData>) => queryOptions<JobsGetJobResponse, JobsGetJobError, JobsGetJobResponse, ReturnType<typeof jobsGetJobQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await ApiClient.__registry.get().jobsGetJob({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: jobsGetJobQueryKey(options)
});

export const jobsListJobsQueryKey = (options?: Options<JobsListJobsData>) => createQueryKey('jobsListJobs', options);

/**
 * List Jobs
 */
export const jobsListJobsOptions = (options?: Options<JobsListJobsData>) => queryOptions<JobsListJobsResponse, JobsListJobsError, JobsListJobsResponse, ReturnType<typeof jobsListJobsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await ApiClient.__registry.get().jobsListJobs({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: jobsListJobsQueryKey(options)
});

/**
 * Create Job
 */
export const jobsCreateJobMutation = (options?: Partial<Options<JobsCreateJobData>>): UseMutationOptions<JobsCreateJobResponse, JobsCreateJobError, Options<JobsCreateJobData>> => {
    const mutationOptions: UseMutationOptions<JobsCreateJobResponse, JobsCreateJobError, Options<JobsCreateJobData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await ApiClient.__registry.get().jobsCreateJob({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Update Job
 */
export const jobsUpdateJobMutation = (options?: Partial<Options<JobsUpdateJobData>>): UseMutationOptions<JobsUpdateJobResponse, JobsUpdateJobError, Options<JobsUpdateJobData>> => {
    const mutationOptions: UseMutationOptions<JobsUpdateJobResponse, JobsUpdateJobError, Options<JobsUpdateJobData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await ApiClient.__registry.get().jobsUpdateJob({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const topicsGetTopicQueryKey = (options: Options<TopicsGetTopicData>) => createQueryKey('topicsGetTopic', options);

/**
 * Get Topic
 */
export const topicsGetTopicOptions = (options: Options<TopicsGetTopicData>) => queryOptions<TopicsGetTopicResponse, TopicsGetTopicError, TopicsGetTopicResponse, ReturnType<typeof topicsGetTopicQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await ApiClient.__registry.get().topicsGetTopic({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: topicsGetTopicQueryKey(options)
});

/**
 * Embed
 */
export const embedEmbedPostMutation = (options?: Partial<Options<EmbedEmbedPostData>>): UseMutationOptions<unknown, EmbedEmbedPostError, Options<EmbedEmbedPostData>> => {
    const mutationOptions: UseMutationOptions<unknown, EmbedEmbedPostError, Options<EmbedEmbedPostData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await ApiClient.__registry.get().embedEmbedPost({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const documentsGetAllQueryKey = (options?: Options<DocumentsGetAllData>) => createQueryKey('documentsGetAll', options);

/**
 * List Documents
 */
export const documentsGetAllOptions = (options?: Options<DocumentsGetAllData>) => queryOptions<DocumentsGetAllResponse, DocumentsGetAllError, DocumentsGetAllResponse, ReturnType<typeof documentsGetAllQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await ApiClient.__registry.get().documentsGetAll({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: documentsGetAllQueryKey(options)
});

const createInfiniteParams = <K extends Pick<QueryKey<Options>[0], 'body' | 'headers' | 'path' | 'query'>>(queryKey: QueryKey<Options>, page: K) => {
    const params = { ...queryKey[0] };
    if (page.body) {
        params.body = {
            ...queryKey[0].body as any,
            ...page.body as any
        };
    }
    if (page.headers) {
        params.headers = {
            ...queryKey[0].headers,
            ...page.headers
        };
    }
    if (page.path) {
        params.path = {
            ...queryKey[0].path as any,
            ...page.path as any
        };
    }
    if (page.query) {
        params.query = {
            ...queryKey[0].query as any,
            ...page.query as any
        };
    }
    return params as unknown as typeof page;
};

export const documentsGetAllInfiniteQueryKey = (options?: Options<DocumentsGetAllData>): QueryKey<Options<DocumentsGetAllData>> => createQueryKey('documentsGetAll', options, true);

/**
 * List Documents
 */
export const documentsGetAllInfiniteOptions = (options?: Options<DocumentsGetAllData>) => {
    const opts = infiniteQueryOptions<DocumentsGetAllResponse, DocumentsGetAllError, InfiniteData<DocumentsGetAllResponse>, QueryKey<Options<DocumentsGetAllData>>, number | Pick<QueryKey<Options<DocumentsGetAllData>>[0], 'body' | 'headers' | 'path' | 'query'>>(
    // @ts-ignore
    {
        queryFn: async ({ pageParam, queryKey, signal }) => {
            // @ts-ignore
            const page: Pick<QueryKey<Options<DocumentsGetAllData>>[0], 'body' | 'headers' | 'path' | 'query'> = typeof pageParam === 'object' ? pageParam : {
                query: {
                    cursor: pageParam
                }
            };
            const params = createInfiniteParams(queryKey, page);
            const { data } = await ApiClient.__registry.get().documentsGetAll({
                ...options,
                ...params,
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: documentsGetAllInfiniteQueryKey(options)
    });
    return opts as Omit<typeof opts, 'initialData'>;
};

export const ontologyGetQueryKey = (options?: Options<OntologyGetData>) => createQueryKey('ontologyGet', options);

/**
 * Get Ontology
 */
export const ontologyGetOptions = (options?: Options<OntologyGetData>) => queryOptions<OntologyGetResponse, OntologyGetError, OntologyGetResponse, ReturnType<typeof ontologyGetQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await ApiClient.__registry.get().ontologyGet({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: ontologyGetQueryKey(options)
});

/**
 * Add Ontology Entry
 */
export const addOntologyEntryMutation = (options?: Partial<Options<AddOntologyEntryData>>): UseMutationOptions<unknown, AddOntologyEntryError, Options<AddOntologyEntryData>> => {
    const mutationOptions: UseMutationOptions<unknown, AddOntologyEntryError, Options<AddOntologyEntryData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await ApiClient.__registry.get().addOntologyEntry({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const ontologyNameExistsQueryKey = (options: Options<OntologyNameExistsData>) => createQueryKey('ontologyNameExists', options);

/**
 * Name Exists
 */
export const ontologyNameExistsOptions = (options: Options<OntologyNameExistsData>) => queryOptions<OntologyNameExistsResponse, OntologyNameExistsError, OntologyNameExistsResponse, ReturnType<typeof ontologyNameExistsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await ApiClient.__registry.get().ontologyNameExists({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: ontologyNameExistsQueryKey(options)
});

export const ontologyGetAnnotationsForDocumentQueryKey = (options: Options<OntologyGetAnnotationsForDocumentData>) => createQueryKey('ontologyGetAnnotationsForDocument', options);

/**
 * Get Annotations For Doc
 */
export const ontologyGetAnnotationsForDocumentOptions = (options: Options<OntologyGetAnnotationsForDocumentData>) => queryOptions<OntologyGetAnnotationsForDocumentResponse, OntologyGetAnnotationsForDocumentError, OntologyGetAnnotationsForDocumentResponse, ReturnType<typeof ontologyGetAnnotationsForDocumentQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await ApiClient.__registry.get().ontologyGetAnnotationsForDocument({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: ontologyGetAnnotationsForDocumentQueryKey(options)
});

/**
 * Update Entry
 */
export const updateOntologyEntryMutation = (options?: Partial<Options<UpdateOntologyEntryData>>): UseMutationOptions<unknown, UpdateOntologyEntryError, Options<UpdateOntologyEntryData>> => {
    const mutationOptions: UseMutationOptions<unknown, UpdateOntologyEntryError, Options<UpdateOntologyEntryData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await ApiClient.__registry.get().updateOntologyEntry({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Delete Entry
 */
export const deleteOntologyEntryMutation = (options?: Partial<Options<DeleteOntologyEntryData>>): UseMutationOptions<unknown, DeleteOntologyEntryError, Options<DeleteOntologyEntryData>> => {
    const mutationOptions: UseMutationOptions<unknown, DeleteOntologyEntryError, Options<DeleteOntologyEntryData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await ApiClient.__registry.get().deleteOntologyEntry({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const ontologyGetNodePathQueryKey = (options: Options<OntologyGetNodePathData>) => createQueryKey('ontologyGetNodePath', options);

/**
 * Get Node Path
 */
export const ontologyGetNodePathOptions = (options: Options<OntologyGetNodePathData>) => queryOptions<OntologyGetNodePathResponse, OntologyGetNodePathError, OntologyGetNodePathResponse, ReturnType<typeof ontologyGetNodePathQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await ApiClient.__registry.get().ontologyGetNodePath({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: ontologyGetNodePathQueryKey(options)
});

export const ontologyGetPotentialMappingsQueryKey = (options?: Options<OntologyGetPotentialMappingsData>) => createQueryKey('ontologyGetPotentialMappings', options);

/**
 * Get Potential Mappings
 */
export const ontologyGetPotentialMappingsOptions = (options?: Options<OntologyGetPotentialMappingsData>) => queryOptions<OntologyGetPotentialMappingsResponse, OntologyGetPotentialMappingsError, OntologyGetPotentialMappingsResponse, ReturnType<typeof ontologyGetPotentialMappingsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await ApiClient.__registry.get().ontologyGetPotentialMappings({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: ontologyGetPotentialMappingsQueryKey(options)
});

/**
 * Metadata Create
 */
export const metadataCreateMutation = (options?: Partial<Options<MetadataCreateData>>): UseMutationOptions<unknown, MetadataCreateError, Options<MetadataCreateData>> => {
    const mutationOptions: UseMutationOptions<unknown, MetadataCreateError, Options<MetadataCreateData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await ApiClient.__registry.get().metadataCreate({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const metadataGetBySourceQueryKey = (options?: Options<MetadataGetBySourceData>) => createQueryKey('metadataGetBySource', options);

/**
 * Get All By Source
 */
export const metadataGetBySourceOptions = (options?: Options<MetadataGetBySourceData>) => queryOptions<MetadataGetBySourceResponse, MetadataGetBySourceError, MetadataGetBySourceResponse, ReturnType<typeof metadataGetBySourceQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await ApiClient.__registry.get().metadataGetBySource({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: metadataGetBySourceQueryKey(options)
});

export const metadataProbeQueryKey = (options?: Options<MetadataProbeData>) => createQueryKey('metadataProbe', options);

/**
 * Get Available
 */
export const metadataProbeOptions = (options?: Options<MetadataProbeData>) => queryOptions<MetadataProbeResponse, MetadataProbeError, MetadataProbeResponse, ReturnType<typeof metadataProbeQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await ApiClient.__registry.get().metadataProbe({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: metadataProbeQueryKey(options)
});

/**
 * Metadata Delete
 */
export const metadataDeleteMutation = (options?: Partial<Options<MetadataDeleteData>>): UseMutationOptions<MetadataDeleteResponse, MetadataDeleteError, Options<MetadataDeleteData>> => {
    const mutationOptions: UseMutationOptions<MetadataDeleteResponse, MetadataDeleteError, Options<MetadataDeleteData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await ApiClient.__registry.get().metadataDelete({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Metadata Update
 */
export const metadataUpdateMutation = (options?: Partial<Options<MetadataUpdateData>>): UseMutationOptions<MetadataUpdateResponse, MetadataUpdateError, Options<MetadataUpdateData>> => {
    const mutationOptions: UseMutationOptions<MetadataUpdateResponse, MetadataUpdateError, Options<MetadataUpdateData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await ApiClient.__registry.get().metadataUpdate({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const precomputedStatsGetByNameQueryKey = (options: Options<PrecomputedStatsGetByNameData>) => createQueryKey('precomputedStatsGetByName', options);

/**
 * Get By Name
 */
export const precomputedStatsGetByNameOptions = (options: Options<PrecomputedStatsGetByNameData>) => queryOptions<PrecomputedStatsGetByNameResponse, PrecomputedStatsGetByNameError, PrecomputedStatsGetByNameResponse, ReturnType<typeof precomputedStatsGetByNameQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await ApiClient.__registry.get().precomputedStatsGetByName({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: precomputedStatsGetByNameQueryKey(options)
});
