// This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod';

import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from './client';
import { client } from './client.gen';
import type { AffinityScoreData, AffinityScoreErrors, AffinityScoreResponses, AnalyticsGetChartDataData, AnalyticsGetChartDataErrors, AnalyticsGetChartDataResponses, AnnotationCountsData, AnnotationCountsErrors, AnnotationCountsResponses, CohortInformationData, CohortInformationErrors, CohortInformationResponses, CohortsData, CohortsErrors, CohortsResponses, EntityCoOccurrenceData, EntityCoOccurrenceErrors, EntityCoOccurrenceResponses, EntityEventsData, EntityEventsErrors, EntityEventsResponses, TopicGetByIdData, TopicGetByIdErrors, TopicGetByIdResponses, TopicScoreData, TopicScoreErrors, TopicScoreResponses, UpdateStatsUpdatestatsPutData, UpdateStatsUpdatestatsPutErrors, UpdateStatsUpdatestatsPutResponses } from './types.gen';
import { zAffinityScoreBody, zAffinityScoreResponse, zAnalyticsGetChartDataBody, zAnalyticsGetChartDataResponse, zAnnotationCountsBody, zAnnotationCountsResponse, zCohortInformationBody, zCohortInformationResponse, zCohortsResponse, zEntityCoOccurrenceBody, zEntityCoOccurrenceResponse, zEntityEventsBody, zEntityEventsResponse, zTopicGetByIdPath, zTopicScoreBody, zTopicScoreResponse } from './zod.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

class HeyApiClient {
    protected client: Client;
    
    constructor(args?: {
        client?: Client;
    }) {
        this.client = args?.client ?? client;
    }
}

class HeyApiRegistry<T> {
    private readonly defaultKey = 'default';
    
    private readonly instances: Map<string, T> = new Map();
    
    get(key?: string): T {
        const instance = this.instances.get(key ?? this.defaultKey);
        if (!instance) {
            throw new Error(`No SDK client found. Create one with "new ApiClient()" to fix this error.`);
        }
        return instance;
    }
    
    set(value: T, key?: string): void {
        this.instances.set(key ?? this.defaultKey, value);
    }
}

export class ApiClient extends HeyApiClient {
    public static readonly __registry: HeyApiRegistry<ApiClient> = new HeyApiRegistry<ApiClient>();
    
    constructor(args?: {
        client?: Client;
        key?: string;
    }) {
        super(args);
        ApiClient.__registry.set(this, args?.key);
    }
    
    /**
     * Get Topic
     */
    public topicGetById<ThrowOnError extends boolean = false>(options: Options<TopicGetByIdData, ThrowOnError>): RequestResult<TopicGetByIdResponses, TopicGetByIdErrors, ThrowOnError> {
        return (options.client ?? this.client).get<TopicGetByIdResponses, TopicGetByIdErrors, ThrowOnError>({
            requestValidator: async (data) => await z.object({
                body: z.never().optional(),
                path: zTopicGetByIdPath,
                query: z.never().optional()
            }).parseAsync(data),
            url: '/topic/{id}',
            ...options
        });
    }
    
    /**
     * Cohort Information
     */
    public cohortInformation<ThrowOnError extends boolean = false>(options: Options<CohortInformationData, ThrowOnError>): RequestResult<CohortInformationResponses, CohortInformationErrors, ThrowOnError> {
        return (options.client ?? this.client).post<CohortInformationResponses, CohortInformationErrors, ThrowOnError>({
            requestValidator: async (data) => await z.object({
                body: zCohortInformationBody,
                path: z.never().optional(),
                query: z.never().optional()
            }).parseAsync(data),
            responseValidator: async (data) => await zCohortInformationResponse.parseAsync(data),
            url: '/cohortinformation',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    /**
     * Cohorts
     */
    public cohorts<ThrowOnError extends boolean = false>(options?: Options<CohortsData, ThrowOnError>): RequestResult<CohortsResponses, CohortsErrors, ThrowOnError> {
        return (options?.client ?? this.client).post<CohortsResponses, CohortsErrors, ThrowOnError>({
            requestValidator: async (data) => await z.object({
                body: z.never().optional(),
                path: z.never().optional(),
                query: z.never().optional()
            }).parseAsync(data),
            responseValidator: async (data) => await zCohortsResponse.parseAsync(data),
            url: '/cohorts',
            ...options
        });
    }
    
    /**
     * Topic Score
     */
    public topicScore<ThrowOnError extends boolean = false>(options: Options<TopicScoreData, ThrowOnError>): RequestResult<TopicScoreResponses, TopicScoreErrors, ThrowOnError> {
        return (options.client ?? this.client).post<TopicScoreResponses, TopicScoreErrors, ThrowOnError>({
            requestValidator: async (data) => await z.object({
                body: zTopicScoreBody,
                path: z.never().optional(),
                query: z.never().optional()
            }).parseAsync(data),
            responseValidator: async (data) => await zTopicScoreResponse.parseAsync(data),
            url: '/topicscore',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    /**
     * Loaners
     */
    public affinityScore<ThrowOnError extends boolean = false>(options: Options<AffinityScoreData, ThrowOnError>): RequestResult<AffinityScoreResponses, AffinityScoreErrors, ThrowOnError> {
        return (options.client ?? this.client).post<AffinityScoreResponses, AffinityScoreErrors, ThrowOnError>({
            requestValidator: async (data) => await z.object({
                body: zAffinityScoreBody,
                path: z.never().optional(),
                query: z.never().optional()
            }).parseAsync(data),
            responseValidator: async (data) => await zAffinityScoreResponse.parseAsync(data),
            url: '/affinity',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    /**
     * Counts
     */
    public annotationCounts<ThrowOnError extends boolean = false>(options: Options<AnnotationCountsData, ThrowOnError>): RequestResult<AnnotationCountsResponses, AnnotationCountsErrors, ThrowOnError> {
        return (options.client ?? this.client).post<AnnotationCountsResponses, AnnotationCountsErrors, ThrowOnError>({
            requestValidator: async (data) => await z.object({
                body: zAnnotationCountsBody,
                path: z.never().optional(),
                query: z.never().optional()
            }).parseAsync(data),
            responseValidator: async (data) => await zAnnotationCountsResponse.parseAsync(data),
            url: '/counts',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    /**
     * Co Occurrence
     */
    public entityCoOccurrence<ThrowOnError extends boolean = false>(options: Options<EntityCoOccurrenceData, ThrowOnError>): RequestResult<EntityCoOccurrenceResponses, EntityCoOccurrenceErrors, ThrowOnError> {
        return (options.client ?? this.client).post<EntityCoOccurrenceResponses, EntityCoOccurrenceErrors, ThrowOnError>({
            requestValidator: async (data) => await z.object({
                body: zEntityCoOccurrenceBody,
                path: z.never().optional(),
                query: z.never().optional()
            }).parseAsync(data),
            responseValidator: async (data) => await zEntityCoOccurrenceResponse.parseAsync(data),
            url: '/cooccurrence',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    /**
     * Update Stats
     */
    public updateStatsUpdatestatsPut<ThrowOnError extends boolean = false>(options?: Options<UpdateStatsUpdatestatsPutData, ThrowOnError>): RequestResult<UpdateStatsUpdatestatsPutResponses, UpdateStatsUpdatestatsPutErrors, ThrowOnError> {
        return (options?.client ?? this.client).put<UpdateStatsUpdatestatsPutResponses, UpdateStatsUpdatestatsPutErrors, ThrowOnError>({
            requestValidator: async (data) => await z.object({
                body: z.never().optional(),
                path: z.never().optional(),
                query: z.never().optional()
            }).parseAsync(data),
            url: '/updatestats',
            ...options
        });
    }
    
    /**
     * Events
     */
    public entityEvents<ThrowOnError extends boolean = false>(options: Options<EntityEventsData, ThrowOnError>): RequestResult<EntityEventsResponses, EntityEventsErrors, ThrowOnError> {
        return (options.client ?? this.client).post<EntityEventsResponses, EntityEventsErrors, ThrowOnError>({
            requestValidator: async (data) => await z.object({
                body: zEntityEventsBody,
                path: z.never().optional(),
                query: z.never().optional()
            }).parseAsync(data),
            responseValidator: async (data) => await zEntityEventsResponse.parseAsync(data),
            url: '/events',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    /**
     * Chart Data
     */
    public analyticsGetChartData<ThrowOnError extends boolean = false>(options: Options<AnalyticsGetChartDataData, ThrowOnError>): RequestResult<AnalyticsGetChartDataResponses, AnalyticsGetChartDataErrors, ThrowOnError> {
        return (options.client ?? this.client).post<AnalyticsGetChartDataResponses, AnalyticsGetChartDataErrors, ThrowOnError>({
            requestValidator: async (data) => await z.object({
                body: zAnalyticsGetChartDataBody,
                path: z.never().optional(),
                query: z.never().optional()
            }).parseAsync(data),
            responseValidator: async (data) => await zAnalyticsGetChartDataResponse.parseAsync(data),
            url: '/charts',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
}
