// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}/analytics` | (string & {});
};

/**
 * AnnotationCoOccurrence
 */
export type AnnotationCoOccurrence = {
    /**
     * E2
     */
    e2: string;
    /**
     * E2Type
     */
    e2Type: string;
    /**
     * Count
     */
    count: number;
};

/**
 * AnnotationCoOccurrenceRequest
 */
export type AnnotationCoOccurrenceRequest = {
    /**
     * Entity
     */
    entity: string;
    /**
     * Value
     */
    value: string;
    /**
     * Targets
     */
    targets: Array<string>;
};

/**
 * AnnotationCoOccurrenceResult
 */
export type AnnotationCoOccurrenceResult = Array<AnnotationCoOccurrence>;

/**
 * AnnotationCohortInformationRequest
 */
export type AnnotationCohortInformationRequest = {
    /**
     * Ids
     */
    ids: Array<string>;
};

/**
 * AnnotationCount
 */
export type AnnotationCount = {
    /**
     * Content
     */
    content: string;
    /**
     * Value
     */
    value: string;
    /**
     * Path
     */
    path: string;
    /**
     * Mention Count
     */
    mention_count: number;
    /**
     * Document Count
     */
    document_count: number;
    /**
     * Sentence Count
     */
    sentence_count: number;
    /**
     * Mentions Per Document
     */
    mentions_per_document: number;
};

/**
 * AnnotationCountsRequest
 */
export type AnnotationCountsRequest = {
    /**
     * Mappings
     */
    mappings: Array<string>;
    /**
     * Page
     */
    page: number;
    /**
     * Page Size
     */
    page_size: number;
    /**
     * Filter
     */
    filter?: string | null;
    /**
     * Order By
     */
    order_by?: 'mention_count' | 'document_count' | 'mentions_per_document' | 'sentence_count';
};

/**
 * AnnotationCountsResult
 */
export type AnnotationCountsResult = {
    /**
     * Items
     */
    items: Array<AnnotationCount>;
    /**
     * Total
     */
    total?: number;
    /**
     * Total Pages
     */
    total_pages?: number;
    /**
     * Next Cursor
     */
    next_cursor?: number | unknown;
    /**
     * Previous Cursor
     */
    previous_cursor?: number | unknown;
};

/**
 * AnnotationEvent
 */
export type AnnotationEvent = {
    /**
     * Text
     */
    text: string;
    /**
     * Sentence
     */
    sentence: string;
    /**
     * Value
     */
    value: string;
    /**
     * A0
     */
    A0: Array<string>;
    /**
     * A1
     */
    A1: Array<string>;
    /**
     * Time
     */
    TIME?: string | null;
    /**
     * Loc
     */
    LOC?: string | null;
};

/**
 * AnnotationEventByType
 */
export type AnnotationEventByType = {
    /**
     * Value
     */
    value: string;
    /**
     * Count
     */
    count: number;
    /**
     * Events
     */
    events: Array<AnnotationEvent>;
};

/**
 * AnnotationEventRequest
 */
export type AnnotationEventRequest = {
    /**
     * Entity
     */
    entity: string;
    /**
     * Value
     */
    value: string;
};

/**
 * AnnotationEventResult
 */
export type AnnotationEventResult = Array<AnnotationEventByType>;

/**
 * AnnotationMetric
 */
export type AnnotationMetric = {
    /**
     * Entityid
     */
    entityId: string;
    /**
     * Entitytype
     */
    entityType: string;
    /**
     * Normscore
     */
    normScore: number;
    /**
     * Rawscore
     */
    rawScore: number;
    /**
     * Category
     */
    category: string;
};

/**
 * AnnotationMetricRequest
 */
export type AnnotationMetricRequest = {
    /**
     * Values
     */
    values: Array<string>;
};

/**
 * AnnotationMetricResult
 */
export type AnnotationMetricResult = Array<AnnotationMetric>;

/**
 * ChartData
 */
export type ChartData = {
    /**
     * Text1
     */
    text1: string;
    /**
     * Value1
     */
    value1: string | number | number;
    /**
     * Documentcount
     */
    documentCount: number;
    /**
     * Sentencecount
     */
    sentenceCount: number;
    /**
     * Mentioncount
     */
    mentionCount: number;
    /**
     * Text2
     */
    text2?: string;
    /**
     * Value2
     */
    value2?: string | number | number;
};

/**
 * ChartDataRequest
 */
export type ChartDataRequest = {
    chart_type?: string | null;
    count_type: CountType;
    x: ChartSeries;
    y?: ChartSeries | unknown;
};

/**
 * ChartResult
 */
export type ChartResult = {
    /**
     * X Total
     */
    x_total: number;
    /**
     * Results
     */
    results: Array<ChartData>;
    /**
     * Y Total
     */
    y_total?: number;
    chart_type: ChartType;
    x_data_type: DataCategory;
    y_data_type: DataCategory | unknown;
    /**
     * X Next Page
     */
    x_next_page?: number | unknown;
    /**
     * Y Next Page
     */
    y_next_page?: number | unknown;
    /**
     * X Prev Page
     */
    x_prev_page?: number | unknown;
    /**
     * Y Prev Page
     */
    y_prev_page?: number | unknown;
};

/**
 * ChartSeries
 */
export type ChartSeries = {
    type: SeriesType;
    /**
     * Value
     */
    value: string;
    /**
     * Formatter
     */
    formatter?: string | unknown;
    /**
     * Page
     */
    page: number;
    /**
     * Page Size
     */
    page_size: number;
    data_type?: DataType;
};

/**
 * ChartType
 */
export type ChartType = 'barchart' | 'heatmap' | 'linechart' | 'scatterplot';

/**
 * CohortClusterEntry
 */
export type CohortClusterEntry = {
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Type
     */
    type: string;
    /**
     * Color
     */
    color: string;
};

/**
 * CohortClusterSimilarity
 */
export type CohortClusterSimilarity = {
    /**
     * Id1
     */
    id1: string;
    /**
     * Id2
     */
    id2: string;
    /**
     * Target
     */
    target: string;
    /**
     * Source
     */
    source: string;
    /**
     * Source Document Count
     */
    source_document_count: number;
    /**
     * Target Document Count
     */
    target_document_count: number;
    /**
     * Similarity
     */
    similarity: number;
};

/**
 * CohortClustering
 */
export type CohortClustering = {
    /**
     * Similarities
     */
    similarities: Array<CohortClusterSimilarity>;
    /**
     * Points
     */
    points: Array<CohortNode>;
    /**
     * Clusters
     */
    clusters: Array<Array<CohortClusterEntry>>;
};

/**
 * CohortInformationEdge
 */
export type CohortInformationEdge = {
    /**
     * Source
     */
    source: string;
    /**
     * Sourceid
     */
    sourceId: string;
    /**
     * Target
     */
    target: string;
    /**
     * Targetid
     */
    targetId: string;
    /**
     * Documentcount
     */
    documentCount: number;
    /**
     * Sentencecount
     */
    sentenceCount: number;
};

/**
 * CohortInformationRank
 */
export type CohortInformationRank = {
    /**
     * Id
     */
    id: string;
    /**
     * Value
     */
    value: number;
};

/**
 * CohortInformationResult
 */
export type CohortInformationResult = {
    /**
     * Edges
     */
    edges: Array<CohortInformationEdge>;
    /**
     * Ranked
     */
    ranked: Array<CohortInformationRank>;
};

/**
 * CohortNode
 */
export type CohortNode = {
    /**
     * Id
     */
    id: string;
    /**
     * Text
     */
    text: string;
    /**
     * Display
     */
    display: string;
    /**
     * Value
     */
    value: number;
    /**
     * R
     */
    r: number;
    /**
     * Color
     */
    color: string;
    /**
     * Cid
     */
    cid: string;
};

/**
 * CountType
 */
export type CountType = 'document' | 'sentence' | 'mention';

/**
 * DataCategory
 */
export type DataCategory = 'string' | 'number' | 'boolean' | 'date' | 'none';

/**
 * DataType
 */
export type DataType = 'string' | 'string_array' | 'int' | 'float' | 'boolean' | 'date';

/**
 * ErrorDetail
 */
export type ErrorDetail = {
    /**
     * Detail
     */
    detail: string;
    /**
     * Code
     */
    code: number;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * SeriesType
 */
export type SeriesType = 'TOPIC' | 'ANNOTATION' | 'DOCUMENT_METADATA' | 'SENTENCE_METADATA' | 'ANNOTATION_METADATA';

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

export type TopicGetByIdData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/topic/{id}';
};

export type TopicGetByIdErrors = {
    /**
     * Not found
     */
    404: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type TopicGetByIdError = TopicGetByIdErrors[keyof TopicGetByIdErrors];

export type TopicGetByIdResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type CohortInformationData = {
    body: AnnotationCohortInformationRequest;
    path?: never;
    query?: never;
    url: '/cohortinformation';
};

export type CohortInformationErrors = {
    /**
     * Bad Request
     */
    400: ErrorDetail;
    /**
     * Unauthorized
     */
    401: ErrorDetail;
    /**
     * Not found
     */
    404: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CohortInformationError = CohortInformationErrors[keyof CohortInformationErrors];

export type CohortInformationResponses = {
    /**
     * Successful Response
     */
    200: CohortInformationResult;
};

export type CohortInformationResponse = CohortInformationResponses[keyof CohortInformationResponses];

export type CohortsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/cohorts';
};

export type CohortsErrors = {
    /**
     * Bad Request
     */
    400: ErrorDetail;
    /**
     * Unauthorized
     */
    401: ErrorDetail;
    /**
     * Not found
     */
    404: unknown;
};

export type CohortsError = CohortsErrors[keyof CohortsErrors];

export type CohortsResponses = {
    /**
     * Successful Response
     */
    200: CohortClustering;
};

export type CohortsResponse = CohortsResponses[keyof CohortsResponses];

export type TopicScoreData = {
    body: AnnotationMetricRequest;
    path?: never;
    query?: never;
    url: '/topicscore';
};

export type TopicScoreErrors = {
    /**
     * Bad Request
     */
    400: ErrorDetail;
    /**
     * Unauthorized
     */
    401: ErrorDetail;
    /**
     * Not found
     */
    404: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type TopicScoreError = TopicScoreErrors[keyof TopicScoreErrors];

export type TopicScoreResponses = {
    /**
     * Successful Response
     */
    200: AnnotationMetricResult;
};

export type TopicScoreResponse = TopicScoreResponses[keyof TopicScoreResponses];

export type AffinityScoreData = {
    body: AnnotationMetricRequest;
    path?: never;
    query?: never;
    url: '/affinity';
};

export type AffinityScoreErrors = {
    /**
     * Bad Request
     */
    400: ErrorDetail;
    /**
     * Unauthorized
     */
    401: ErrorDetail;
    /**
     * Not found
     */
    404: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AffinityScoreError = AffinityScoreErrors[keyof AffinityScoreErrors];

export type AffinityScoreResponses = {
    /**
     * Successful Response
     */
    200: AnnotationMetricResult;
};

export type AffinityScoreResponse = AffinityScoreResponses[keyof AffinityScoreResponses];

export type AnnotationCountsData = {
    body: AnnotationCountsRequest;
    path?: never;
    query?: never;
    url: '/counts';
};

export type AnnotationCountsErrors = {
    /**
     * Bad Request
     */
    400: ErrorDetail;
    /**
     * Unauthorized
     */
    401: ErrorDetail;
    /**
     * Not found
     */
    404: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AnnotationCountsError = AnnotationCountsErrors[keyof AnnotationCountsErrors];

export type AnnotationCountsResponses = {
    /**
     * Successful Response
     */
    200: AnnotationCountsResult;
};

export type AnnotationCountsResponse = AnnotationCountsResponses[keyof AnnotationCountsResponses];

export type EntityCoOccurrenceData = {
    body: AnnotationCoOccurrenceRequest;
    path?: never;
    query?: never;
    url: '/cooccurrence';
};

export type EntityCoOccurrenceErrors = {
    /**
     * Bad Request
     */
    400: ErrorDetail;
    /**
     * Unauthorized
     */
    401: ErrorDetail;
    /**
     * Not found
     */
    404: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type EntityCoOccurrenceError = EntityCoOccurrenceErrors[keyof EntityCoOccurrenceErrors];

export type EntityCoOccurrenceResponses = {
    /**
     * Successful Response
     */
    200: AnnotationCoOccurrenceResult;
};

export type EntityCoOccurrenceResponse = EntityCoOccurrenceResponses[keyof EntityCoOccurrenceResponses];

export type UpdateStatsUpdatestatsPutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/updatestats';
};

export type UpdateStatsUpdatestatsPutErrors = {
    /**
     * Not found
     */
    404: unknown;
};

export type UpdateStatsUpdatestatsPutResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type EntityEventsData = {
    body: AnnotationEventRequest;
    path?: never;
    query?: never;
    url: '/events';
};

export type EntityEventsErrors = {
    /**
     * Bad Request
     */
    400: ErrorDetail;
    /**
     * Unauthorized
     */
    401: ErrorDetail;
    /**
     * Not found
     */
    404: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type EntityEventsError = EntityEventsErrors[keyof EntityEventsErrors];

export type EntityEventsResponses = {
    /**
     * Successful Response
     */
    200: AnnotationEventResult;
};

export type EntityEventsResponse = EntityEventsResponses[keyof EntityEventsResponses];

export type AnalyticsGetChartDataData = {
    body: ChartDataRequest;
    path?: never;
    query?: never;
    url: '/charts';
};

export type AnalyticsGetChartDataErrors = {
    /**
     * Bad Request
     */
    400: ErrorDetail;
    /**
     * Unauthorized
     */
    401: ErrorDetail;
    /**
     * Not Found
     */
    404: ErrorDetail;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AnalyticsGetChartDataError = AnalyticsGetChartDataErrors[keyof AnalyticsGetChartDataErrors];

export type AnalyticsGetChartDataResponses = {
    /**
     * Successful Response
     */
    200: ChartResult;
};

export type AnalyticsGetChartDataResponse = AnalyticsGetChartDataResponses[keyof AnalyticsGetChartDataResponses];
