// This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod';

/**
 * AnnotationCoOccurrence
 */
export const zAnnotationCoOccurrence = z.object({
    e2: z.string(),
    e2Type: z.string(),
    count: z.number()
});

/**
 * AnnotationCoOccurrenceRequest
 */
export const zAnnotationCoOccurrenceRequest = z.object({
    entity: z.string(),
    value: z.string(),
    targets: z.array(z.string())
});

/**
 * AnnotationCoOccurrenceResult
 */
export const zAnnotationCoOccurrenceResult = z.array(zAnnotationCoOccurrence);

/**
 * AnnotationCohortInformationRequest
 */
export const zAnnotationCohortInformationRequest = z.object({
    ids: z.array(z.string())
});

/**
 * AnnotationCount
 */
export const zAnnotationCount = z.object({
    content: z.string(),
    value: z.string(),
    path: z.string(),
    mention_count: z.int(),
    document_count: z.int(),
    sentence_count: z.int(),
    mentions_per_document: z.number()
});

/**
 * AnnotationCountsRequest
 */
export const zAnnotationCountsRequest = z.object({
    mappings: z.array(z.string()),
    page: z.int(),
    page_size: z.int(),
    filter: z.string().nullish(),
    order_by: z.enum([
        'mention_count',
        'document_count',
        'mentions_per_document',
        'sentence_count'
    ]).optional().default('mention_count')
});

/**
 * AnnotationCountsResult
 */
export const zAnnotationCountsResult = z.object({
    items: z.array(zAnnotationCount),
    total: z.int().optional().default(0),
    total_pages: z.int().optional().default(0),
    next_cursor: z.union([
        z.int(),
        z.unknown()
    ]).optional(),
    previous_cursor: z.union([
        z.int(),
        z.unknown()
    ]).optional()
});

/**
 * AnnotationEvent
 */
export const zAnnotationEvent = z.object({
    text: z.string(),
    sentence: z.string(),
    value: z.string(),
    A0: z.array(z.string()),
    A1: z.array(z.string()),
    TIME: z.string().nullish(),
    LOC: z.string().nullish()
});

/**
 * AnnotationEventByType
 */
export const zAnnotationEventByType = z.object({
    value: z.string(),
    count: z.int(),
    events: z.array(zAnnotationEvent)
});

/**
 * AnnotationEventRequest
 */
export const zAnnotationEventRequest = z.object({
    entity: z.string(),
    value: z.string()
});

/**
 * AnnotationEventResult
 */
export const zAnnotationEventResult = z.array(zAnnotationEventByType);

/**
 * AnnotationMetric
 */
export const zAnnotationMetric = z.object({
    entityId: z.string(),
    entityType: z.string(),
    normScore: z.number(),
    rawScore: z.number(),
    category: z.string()
});

/**
 * AnnotationMetricRequest
 */
export const zAnnotationMetricRequest = z.object({
    values: z.array(z.string())
});

/**
 * AnnotationMetricResult
 */
export const zAnnotationMetricResult = z.array(zAnnotationMetric);

/**
 * ChartData
 */
export const zChartData = z.object({
    text1: z.string(),
    value1: z.union([
        z.string(),
        z.int(),
        z.number()
    ]),
    documentCount: z.int(),
    sentenceCount: z.int(),
    mentionCount: z.int(),
    text2: z.string().optional().default(''),
    value2: z.union([
        z.string(),
        z.int(),
        z.number()
    ]).optional()
});

/**
 * ChartType
 */
export const zChartType = z.enum([
    'barchart',
    'heatmap',
    'linechart',
    'scatterplot'
]);

/**
 * CohortClusterEntry
 */
export const zCohortClusterEntry = z.object({
    id: z.string(),
    name: z.string(),
    type: z.string(),
    color: z.string()
});

/**
 * CohortClusterSimilarity
 */
export const zCohortClusterSimilarity = z.object({
    id1: z.string(),
    id2: z.string(),
    target: z.string(),
    source: z.string(),
    source_document_count: z.int(),
    target_document_count: z.int(),
    similarity: z.number()
});

/**
 * CohortInformationEdge
 */
export const zCohortInformationEdge = z.object({
    source: z.string(),
    sourceId: z.string(),
    target: z.string(),
    targetId: z.string(),
    documentCount: z.int(),
    sentenceCount: z.int()
});

/**
 * CohortInformationRank
 */
export const zCohortInformationRank = z.object({
    id: z.string(),
    value: z.int()
});

/**
 * CohortInformationResult
 */
export const zCohortInformationResult = z.object({
    edges: z.array(zCohortInformationEdge),
    ranked: z.array(zCohortInformationRank)
});

/**
 * CohortNode
 */
export const zCohortNode = z.object({
    id: z.string(),
    text: z.string(),
    display: z.string(),
    value: z.number(),
    r: z.int(),
    color: z.string(),
    cid: z.string()
});

/**
 * CohortClustering
 */
export const zCohortClustering = z.object({
    similarities: z.array(zCohortClusterSimilarity),
    points: z.array(zCohortNode),
    clusters: z.array(z.array(zCohortClusterEntry))
});

/**
 * CountType
 */
export const zCountType = z.enum([
    'document',
    'sentence',
    'mention'
]);

/**
 * DataCategory
 */
export const zDataCategory = z.enum([
    'string',
    'number',
    'boolean',
    'date',
    'none'
]);

/**
 * ChartResult
 */
export const zChartResult = z.object({
    x_total: z.int(),
    results: z.array(zChartData),
    y_total: z.int().optional().default(0),
    chart_type: zChartType,
    x_data_type: zDataCategory,
    y_data_type: z.union([
        zDataCategory,
        z.unknown()
    ]),
    x_next_page: z.union([
        z.int(),
        z.unknown()
    ]).optional(),
    y_next_page: z.union([
        z.int(),
        z.unknown()
    ]).optional(),
    x_prev_page: z.union([
        z.int(),
        z.unknown()
    ]).optional(),
    y_prev_page: z.union([
        z.int(),
        z.unknown()
    ]).optional()
});

/**
 * DataType
 */
export const zDataType = z.enum([
    'string',
    'string_array',
    'int',
    'float',
    'boolean',
    'date'
]);

/**
 * ErrorDetail
 */
export const zErrorDetail = z.object({
    detail: z.string(),
    code: z.int()
});

/**
 * JobStatus
 */
export const zJobStatus = z.enum([
    'waiting',
    'running',
    'completed',
    'cancelled',
    'failed'
]);

/**
 * JobType
 */
export const zJobType = z.enum([
    'annotation',
    'update',
    'analyticsupdate',
    'other'
]);

/**
 * Job
 */
export const zJob = z.object({
    id: z.int(),
    name: z.string(),
    status: zJobStatus,
    type_: zJobType,
    user_id: z.string(),
    total: z.int(),
    completed: z.int(),
    failed: z.int(),
    created_at: z.iso.datetime({ local: true }),
    started_at: z.iso.datetime({ local: true }).nullish(),
    completed_at: z.iso.datetime({ local: true }).nullish(),
    metadata_json: z.record(z.string(), z.unknown()).optional(),
    deleting: z.boolean().optional().default(false)
});

/**
 * SeriesType
 */
export const zSeriesType = z.enum([
    'TOPIC',
    'ANNOTATION',
    'DOCUMENT_METADATA',
    'SENTENCE_METADATA',
    'ANNOTATION_METADATA'
]);

/**
 * ChartSeries
 */
export const zChartSeries = z.object({
    type: zSeriesType,
    value: z.string(),
    formatter: z.union([
        z.string(),
        z.unknown()
    ]).optional(),
    page: z.int(),
    page_size: z.int(),
    data_type: zDataType.optional()
});

/**
 * ChartDataRequest
 */
export const zChartDataRequest = z.object({
    chart_type: z.string().nullish(),
    count_type: zCountType,
    x: zChartSeries,
    y: z.union([
        zChartSeries,
        z.unknown()
    ]).optional()
});

/**
 * ValidationError
 */
export const zValidationError = z.object({
    loc: z.array(z.union([z.string(), z.int()])),
    msg: z.string(),
    type: z.string(),
    input: z.unknown().optional(),
    ctx: z.record(z.string(), z.unknown()).optional()
});

/**
 * HTTPValidationError
 */
export const zHttpValidationError = z.object({
    detail: z.array(zValidationError).optional()
});

export const zTopicGetByIdPath = z.object({
    id: z.string()
});

export const zCohortInformationBody = zAnnotationCohortInformationRequest;

/**
 * Successful Response
 */
export const zCohortInformationResponse = zCohortInformationResult;

/**
 * Successful Response
 */
export const zCohortsResponse = zCohortClustering;

export const zTopicScoreBody = zAnnotationMetricRequest;

/**
 * Successful Response
 */
export const zTopicScoreResponse = zAnnotationMetricResult;

export const zAffinityScoreBody = zAnnotationMetricRequest;

/**
 * Successful Response
 */
export const zAffinityScoreResponse = zAnnotationMetricResult;

export const zAnnotationCountsBody = zAnnotationCountsRequest;

/**
 * Successful Response
 */
export const zAnnotationCountsResponse = zAnnotationCountsResult;

export const zEntityCoOccurrenceBody = zAnnotationCoOccurrenceRequest;

/**
 * Successful Response
 */
export const zEntityCoOccurrenceResponse = zAnnotationCoOccurrenceResult;

export const zAnalysisUpdateStatsBody = zJob;

/**
 * Response 200 Analysisupdatestats
 *
 * Successful Response
 */
export const zAnalysisUpdateStatsResponse = z.boolean();

export const zEntityEventsBody = zAnnotationEventRequest;

/**
 * Successful Response
 */
export const zEntityEventsResponse = zAnnotationEventResult;

export const zAnalyticsGetChartDataBody = zChartDataRequest;

/**
 * Successful Response
 */
export const zAnalyticsGetChartDataResponse = zChartResult;
