# AUTOGENERATED FROM drizzle-schema.json. DO NOT EDIT BY HAND.

import uuid

from pgvector.sqlalchemy import HALFVEC, Vector
from sqlalchemy import (
    ARRAY,
    JSON,
    UUID,
    BigInteger,
    Boolean,
    Column,
    Date,
    DateTime,
    Enum,
    Float,
    ForeignKey,
    Integer,
    Numeric,
    String,
    Text,
    text,
)
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.orm import declarative_base, relationship

from lang3s import config

Base = declarative_base()


class UserTable(Base):
    __tablename__ = "user"

    id = Column("id", Text, primary_key=True, nullable=False)
    name = Column("name", Text, nullable=False)
    email = Column("email", Text, nullable=False, unique=True)
    emailVerified = Column("email_verified", Boolean, nullable=False)
    image = Column("image", Text, nullable=True)
    createdAt = Column("created_at", DateTime, nullable=False)
    updatedAt = Column("updated_at", DateTime, nullable=False)
    role = Column("role", Text, nullable=True)
    banned = Column("banned", Boolean, nullable=True)
    banReason = Column("ban_reason", Text, nullable=True)
    banExpires = Column("ban_expires", DateTime, nullable=True)
    username = Column("username", Text, nullable=True, unique=True)
    displayUsername = Column("display_username", Text, nullable=True)

    session_collection = relationship(
        "SessionTable", back_populates="user", cascade="all, delete-orphan"
    )
    account_collection = relationship(
        "AccountTable", back_populates="user", cascade="all, delete-orphan"
    )
    apikey_collection = relationship(
        "ApikeyTable", back_populates="user", cascade="all, delete-orphan"
    )
    jobs_collection = relationship(
        "JobsTable", back_populates="user", cascade="all, delete-orphan"
    )

    def __repr__(self) -> str:  # pragma: no cover
        return f"<%s id={self.id}>" % self.__class__.__name__


class SessionTable(Base):
    __tablename__ = "session"

    id = Column("id", Text, primary_key=True, nullable=False)
    expiresAt = Column("expires_at", DateTime, nullable=False)
    token = Column("token", Text, nullable=False, unique=True)
    createdAt = Column("created_at", DateTime, nullable=False)
    updatedAt = Column("updated_at", DateTime, nullable=False)
    ipAddress = Column("ip_address", Text, nullable=True)
    userAgent = Column("user_agent", Text, nullable=True)
    userId = Column(
        "user_id", Text, ForeignKey("user.id", ondelete="cascade"), nullable=False
    )
    impersonatedBy = Column("impersonated_by", Text, nullable=True)

    user = relationship("UserTable", back_populates="session_collection")

    def __repr__(self) -> str:  # pragma: no cover
        return f"<%s id={self.id}>" % self.__class__.__name__


class AccountTable(Base):
    __tablename__ = "account"

    id = Column("id", Text, primary_key=True, nullable=False)
    accountId = Column("account_id", Text, nullable=False)
    providerId = Column("provider_id", Text, nullable=False)
    userId = Column(
        "user_id", Text, ForeignKey("user.id", ondelete="cascade"), nullable=False
    )
    accessToken = Column("access_token", Text, nullable=True)
    refreshToken = Column("refresh_token", Text, nullable=True)
    idToken = Column("id_token", Text, nullable=True)
    accessTokenExpiresAt = Column("access_token_expires_at", DateTime, nullable=True)
    refreshTokenExpiresAt = Column("refresh_token_expires_at", DateTime, nullable=True)
    scope = Column("scope", Text, nullable=True)
    password = Column("password", Text, nullable=True)
    createdAt = Column("created_at", DateTime, nullable=False)
    updatedAt = Column("updated_at", DateTime, nullable=False)

    user = relationship("UserTable", back_populates="account_collection")

    def __repr__(self) -> str:  # pragma: no cover
        return f"<%s id={self.id}>" % self.__class__.__name__


class VerificationTable(Base):
    __tablename__ = "verification"

    id = Column("id", Text, primary_key=True, nullable=False)
    identifier = Column("identifier", Text, nullable=False)
    value = Column("value", Text, nullable=False)
    expiresAt = Column("expires_at", DateTime, nullable=False)
    createdAt = Column("created_at", DateTime, nullable=False)
    updatedAt = Column("updated_at", DateTime, nullable=False)

    def __repr__(self) -> str:  # pragma: no cover
        return f"<%s id={self.id}>" % self.__class__.__name__


class ApikeyTable(Base):
    __tablename__ = "apikey"

    id = Column("id", Text, primary_key=True, nullable=False)
    name = Column("name", Text, nullable=True)
    start = Column("start", Text, nullable=True)
    prefix = Column("prefix", Text, nullable=True)
    key = Column("key", Text, nullable=False)
    userId = Column(
        "user_id", Text, ForeignKey("user.id", ondelete="cascade"), nullable=False
    )
    refillInterval = Column("refill_interval", Integer, nullable=True)
    refillAmount = Column("refill_amount", Integer, nullable=True)
    lastRefillAt = Column("last_refill_at", DateTime, nullable=True)
    enabled = Column("enabled", Boolean, nullable=True)
    rateLimitEnabled = Column("rate_limit_enabled", Boolean, nullable=True)
    rateLimitTimeWindow = Column("rate_limit_time_window", Integer, nullable=True)
    rateLimitMax = Column("rate_limit_max", Integer, nullable=True)
    requestCount = Column("request_count", Integer, nullable=True)
    remaining = Column("remaining", Integer, nullable=True)
    lastRequest = Column("last_request", DateTime, nullable=True)
    expiresAt = Column("expires_at", DateTime, nullable=True)
    createdAt = Column("created_at", DateTime, nullable=False)
    updatedAt = Column("updated_at", DateTime, nullable=False)
    permissions = Column("permissions", Text, nullable=True)
    metadata_ = Column("metadata", Text, nullable=True)

    user = relationship("UserTable", back_populates="apikey_collection")

    def __repr__(self) -> str:  # pragma: no cover
        return f"<%s id={self.id}>" % self.__class__.__name__


class ConfigurationTable(Base):
    __tablename__ = "configuration"

    name = Column("name", Text, primary_key=True, nullable=False)
    value = Column("value", JSONB, nullable=False)

    def __repr__(self) -> str:  # pragma: no cover
        return "<%s>" % self.__class__.__name__


class JobsTable(Base):
    __tablename__ = "jobs"

    id = Column("id", Integer, primary_key=True, nullable=False)
    name = Column("name", String, nullable=False)
    apiKey = Column("apiKey", Text, nullable=True)
    userId = Column(
        "user_id", Text, ForeignKey("user.id", ondelete="cascade"), nullable=False
    )
    status = Column(
        "status",
        Enum("waiting", "processing", "complete", "failed", name="job_status"),
        nullable=False,
    )
    total = Column("total", Integer, nullable=False)
    completed = Column("completed", Integer, nullable=False)
    failed = Column("failed", Integer, nullable=False)
    jobType = Column(
        "job_type",
        Enum("annotation", "update", "other", name="job_type"),
        nullable=False,
    )
    metadata_ = Column("metadata", JSON, nullable=False)
    createdAt = Column("created_at", DateTime, nullable=True)
    startedAt = Column("started_at", DateTime, nullable=True)
    completedAt = Column("completed_at", DateTime, nullable=True)
    updatedAt = Column("updated_at", DateTime, nullable=True)

    user = relationship("UserTable", back_populates="jobs_collection")

    def __repr__(self) -> str:  # pragma: no cover
        return f"<%s id={self.id}>" % self.__class__.__name__


class MetadataTable(Base):
    __tablename__ = "metadata"

    id = Column(
        "id",
        UUID(as_uuid=True),
        primary_key=True,
        nullable=False,
        server_default=text("gen_random_uuid()"),
    )
    source = Column(
        "source",
        Enum("document", "annotation", "sentence", name="metadata_sources"),
        nullable=False,
    )
    name = Column("name", Text, nullable=False)
    dataType = Column(
        "data_type",
        Enum(
            "string",
            "string[]",
            "int",
            "float",
            "boolean",
            "date",
            name="metadata_data_type",
        ),
        nullable=False,
    )
    formatter = Column("formatter", Text, nullable=True)
    linksToDocumentId = Column("links_to_document_id", Boolean, nullable=False)
    linksToMetadataId = Column("metadata_link", UUID(as_uuid=True), nullable=True)

    def __repr__(self) -> str:  # pragma: no cover
        return f"<%s id={self.id}>" % self.__class__.__name__


class OntologyTable(Base):
    __tablename__ = "ontology"

    id = Column("id", Integer, primary_key=True, nullable=False)
    name = Column("name", Text, nullable=False, unique=True)
    parentId = Column("parent_id", Integer, nullable=True)
    description = Column("description", Text, nullable=True)
    color = Column("color", Text, nullable=False)
    isAttribute = Column("is_attribute", Boolean, nullable=False)
    path = Column("path", Text, nullable=False)
    properties = Column("properties", JSONB, nullable=True)

    annotation_to_ontology_collection = relationship(
        "AnnotationToOntologyTable",
        back_populates="ontology",
        cascade="all, delete-orphan",
    )

    def __repr__(self) -> str:  # pragma: no cover
        return f"<%s id={self.id}>" % self.__class__.__name__


class AnnotationToOntologyTable(Base):
    __tablename__ = "annotation_to_ontology"

    id = Column("id", Integer, primary_key=True, nullable=False)
    ontologyId = Column(
        "ontology_id",
        Integer,
        ForeignKey("ontology.id", ondelete="cascade"),
        nullable=False,
    )
    annotation = Column("annotation_type_value", Text, nullable=False)

    ontology = relationship(
        "OntologyTable", back_populates="annotation_to_ontology_collection"
    )

    def __repr__(self) -> str:  # pragma: no cover
        return f"<%s id={self.id}>" % self.__class__.__name__


class PrecomputedStatsTable(Base):
    __tablename__ = "precomputed_stats"

    id = Column("id", Integer, primary_key=True, nullable=False)
    name = Column("name", Text, nullable=False)
    value = Column("value", JSONB, nullable=False)

    def __repr__(self) -> str:  # pragma: no cover
        return f"<%s id={self.id}>" % self.__class__.__name__


class DocumentsTable(Base):
    __tablename__ = "documents"

    id = Column("id", Text, primary_key=True, nullable=False)
    title = Column("title", Text, nullable=False)
    metadata_ = Column("metadata", JSONB, nullable=False)
    createdAt = Column("created_at", DateTime, nullable=True)
    updatedAt = Column("updated_at", DateTime, nullable=True)

    text_collection = relationship(
        "TextTable", back_populates="document", cascade="all, delete-orphan"
    )
    text_annotations_collection = relationship(
        "TextAnnotationsTable", back_populates="document", cascade="all, delete-orphan"
    )
    keywords_collection = relationship(
        "KeywordsTable", back_populates="document", cascade="all, delete-orphan"
    )
    claims_collection = relationship(
        "ClaimsTable", back_populates="document", cascade="all, delete-orphan"
    )

    def __repr__(self) -> str:  # pragma: no cover
        return f"<%s id={self.id}>" % self.__class__.__name__


class TextTable(Base):
    __tablename__ = "text"

    id = Column("id", Text, primary_key=True, nullable=False)
    content = Column("text", Text, nullable=False)
    embedding = Column(
        "embedding", HALFVEC(config.SEMANTIC_EMBEDDING_DIMENSION), nullable=False
    )
    documentId = Column(
        "doc_id", Text, ForeignKey("documents.id", ondelete="cascade"), nullable=False
    )
    metadata_ = Column("metadata", JSONB, nullable=False)
    createdAt = Column("created_at", DateTime, nullable=True)
    updatedAt = Column("updated_at", DateTime, nullable=True)

    document = relationship("DocumentsTable", back_populates="text_collection")
    text_annotations_collection = relationship(
        "TextAnnotationsTable", back_populates="text", cascade="all, delete-orphan"
    )
    keywords_collection = relationship(
        "KeywordsTable", back_populates="text", cascade="all, delete-orphan"
    )

    def __repr__(self) -> str:  # pragma: no cover
        return f"<%s id={self.id}>" % self.__class__.__name__


class TextAnnotationsTable(Base):
    __tablename__ = "text_annotations"

    id = Column("id", Text, primary_key=True, nullable=False)
    content = Column("text", Text, nullable=False)
    cleaned = Column("clean_text", Text, nullable=False)
    normalized = Column("normalized_text", Text, nullable=False)
    textId = Column(
        "text_id", Text, ForeignKey("text.id", ondelete="cascade"), nullable=False
    )
    documentId = Column(
        "doc_id", Text, ForeignKey("documents.id", ondelete="cascade"), nullable=False
    )
    start = Column("start", Integer, nullable=False)
    end = Column("end", Integer, nullable=False)
    sentenceId = Column("sentence_id", Integer, nullable=False)
    sentenceAid = Column("sentence_aid", Text, nullable=False)
    type_ = Column("type", Text, nullable=False)
    value = Column("value", Text, nullable=False)
    source = Column("source", Text, nullable=False)
    mapping = Column("mapping", Text, nullable=True)
    embedding = Column(
        "embedding", HALFVEC(config.SEMANTIC_EMBEDDING_DIMENSION), nullable=False
    )
    metadata_ = Column("metadata", JSONB, nullable=False)
    createdAt = Column("created_at", DateTime, nullable=True)
    updatedAt = Column("updated_at", DateTime, nullable=True)
    a0Text = Column("a0_text", ARRAY(Text), nullable=True)
    a1Text = Column("a1_text", ARRAY(Text), nullable=True)
    timeText = Column("time_text", Text, nullable=True)
    locText = Column("loc_text", Text, nullable=True)
    a0Id = Column("a0_id", ARRAY(Text), nullable=True)
    a1Id = Column("a1_id", ARRAY(Text), nullable=True)
    timeId = Column("time_id", Text, nullable=True)
    locId = Column("loc_id", Text, nullable=True)

    text = relationship("TextTable", back_populates="text_annotations_collection")
    document = relationship(
        "DocumentsTable", back_populates="text_annotations_collection"
    )

    def __repr__(self) -> str:  # pragma: no cover
        return f"<%s id={self.id}>" % self.__class__.__name__


class KeywordsTable(Base):
    __tablename__ = "keywords"

    id = Column(
        "id",
        UUID(as_uuid=True),
        primary_key=True,
        nullable=False,
        server_default=text("gen_random_uuid()"),
    )
    category = Column("category", Text, nullable=True)
    keyword = Column("keyword", Text, nullable=False)
    documentId = Column(
        "document_id",
        Text,
        ForeignKey("documents.id", ondelete="cascade"),
        nullable=False,
    )
    textId = Column(
        "text_id", Text, ForeignKey("text.id", ondelete="cascade"), nullable=False
    )
    embedding = Column(
        "embedding", HALFVEC(config.SEMANTIC_EMBEDDING_DIMENSION), nullable=False
    )

    document = relationship("DocumentsTable", back_populates="keywords_collection")
    text = relationship("TextTable", back_populates="keywords_collection")

    def __repr__(self) -> str:  # pragma: no cover
        return f"<%s id={self.id}>" % self.__class__.__name__


class ClaimsTable(Base):
    __tablename__ = "claims"

    id = Column(
        "id",
        UUID(as_uuid=True),
        primary_key=True,
        nullable=False,
        server_default=text("gen_random_uuid()"),
    )
    documentId = Column(
        "doc_id", Text, ForeignKey("documents.id", ondelete="cascade"), nullable=False
    )
    claim = Column("claim", Text, nullable=False)
    type_ = Column("claim_type", Text, nullable=False)
    source = Column("source", Text, nullable=True)
    subject = Column("subject", Text, nullable=False)
    predicate = Column("predicate", Text, nullable=False)
    object = Column("object", Text, nullable=False)
    stance = Column("stance", Text, nullable=False)
    certainty = Column("certainty", Text, nullable=False)
    modality = Column("modality", Text, nullable=False)
    negation = Column("negation", Boolean, nullable=False)
    condition = Column("condition", Text, nullable=False)
    time = Column("time", Text, nullable=False)
    location = Column("location", Text, nullable=False)
    evidence = Column("evidence", Text, nullable=False)
    sentiment = Column(
        "sentiment",
        Enum("positive", "negative", "neutral", name="sentimentEnum"),
        nullable=False,
    )
    keywords = Column("keywords", ARRAY(Text), nullable=False)
    embedding = Column(
        "embedding", HALFVEC(config.SEMANTIC_EMBEDDING_DIMENSION), nullable=False
    )
    createdAt = Column("created_at", DateTime, nullable=True)
    updatedAt = Column("updated_at", DateTime, nullable=True)

    document = relationship("DocumentsTable", back_populates="claims_collection")

    def __repr__(self) -> str:  # pragma: no cover
        return f"<%s id={self.id}>" % self.__class__.__name__


class TopicsTable(Base):
    __tablename__ = "topics"

    id = Column("id", Text, primary_key=True, nullable=False)
    name = Column("name", Text, nullable=False)
    fixed = Column("is_fixed", Boolean, nullable=False)
    embedding = Column(
        "embedding", HALFVEC(config.SEMANTIC_EMBEDDING_DIMENSION), nullable=False
    )
    support = Column("support", Integer, nullable=False)
    documents = Column("doc_support", Integer, nullable=False)
    createdAt = Column("created_at", DateTime, nullable=True)
    updatedAt = Column("updated_at", DateTime, nullable=True)

    tree_collection = relationship(
        "TopicTreeTopicMapTable", back_populates="topic", cascade="all, delete-orphan"
    )

    def __repr__(self) -> str:  # pragma: no cover
        return f"<%s id={self.id}>" % self.__class__.__name__


class TopicsTreeTable(Base):
    __tablename__ = "topics_tree"

    id = Column("id", Text, primary_key=True, nullable=False)
    name = Column("name", Text, nullable=False)
    parent = Column("parent_id", Text, nullable=True)
    isLeaf = Column("is_leaf", Boolean, nullable=True)
    level = Column("level", Integer, nullable=True)
    splitK = Column("split_k", Integer, nullable=True)
    createdAt = Column("created_at", DateTime, nullable=True)
    updatedAt = Column("updated_at", DateTime, nullable=True)

    tree_collection = relationship(
        "TopicTreeTopicMapTable",
        back_populates="node",
        cascade="all, delete-orphan",
    )

    def __repr__(self) -> str:  # pragma: no cover
        return f"<%s id={self.id}>" % self.__class__.__name__


class TopicTreeTopicMapTable(Base):
    __tablename__ = "topic_tree_topic_map"

    id = Column("id", Integer, primary_key=True, nullable=False)
    nodeId = Column(
        "node_id", Text, ForeignKey("topics_tree.id", ondelete="cascade"), nullable=True
    )
    topicId = Column(
        "topic_id", Text, ForeignKey("topics.id", ondelete="cascade"), nullable=True
    )

    node = relationship("TopicsTreeTable", back_populates="tree_collection")
    topic = relationship("TopicsTable", back_populates="tree_collection")

    def __repr__(self) -> str:  # pragma: no cover
        return f"<%s id={self.id}>" % self.__class__.__name__
