[project]
name = "lang3s"
version = "2025.10.3"
description = "Lang3s"
readme = "README.md"

[tool.poetry]
name = "lang3s"
version = "2025.10.3"
description = "Lang3s"
authors = ["David Bracewell"]
readme = "README.md"


packages = [
    { include = "lang3s", from = "src" }
]

include = [
    { path = "**/*.so" },
    { path = "**/*.pyd" },
    { path = "**/*.dll" },
]


[build-system]
requires = ["setuptools>=65", "wheel", "Cython>=3.0"]
build-backend = "setuptools.build_meta"

[tool.poetry.dependencies]
python = "^3.11,<=3.13"
transformers = "4.51.3"
torch = "2.8.0"
datasets = "*"
scikit-learn = "*"
evaluate = "*"
seqeval = "*"
accelerate = "*"
shortuuid = "1.0.13"
spacy = "3.8.7"
lingua_language_detector = "2.1.1"
pgvector = "0.4.1"
inngest = "0.5.9"
fastapi = "*"
spacy_download = "1.1.0"
uvicorn = "*"
redis = "7.0.0"
bertopic = ">=0.17.3,<0.18.0"
lang3s-job-service = { path = "/Users/ik/prj/Lang3s/backend/jobs_service" }
jsonlines = ">=4.0.0,<5.0.0"
hnswlib = ">=0.8.0,<0.9.0"
psycopg = { version = ">=3.2.12,<4.0.0", extras = ["binary", "pgvector"] }
psycopg-pool = ">=3.2.7,<4.0.0"
pytorch-crf = ">=0.7.2,<0.8.0"
fastcoref = ">=2.1.6,<3.0.0"
openai = ">=2.7.2,<3.0.0"
more-itertools = ">=10.8.0,<11.0.0"
numpy = "2.3.4"


[tool.poetry.group.dev.dependencies]
pytest = "^8.0"
cython = "^3.2.1"

[tool.setuptools]
package-dir = { "" = "src" }