[supervisord]
nodaemon=true

[program:rest_api]
command=python /app/rest_api.py
autorestart=true
redirect_stderr=true
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr

[program:kafka_consumer]
command=python /app/kafka_consumer.py
autorestart=true
redirect_stderr=true
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr
