// This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod';

import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from './client';
import { client } from './client.gen';
import type { AddOntologyEntryData, AddOntologyEntryErrors, AddOntologyEntryResponses, DeleteOntologyEntryData, DeleteOntologyEntryErrors, DeleteOntologyEntryResponses, DocumentsGetAllData, DocumentsGetAllErrors, DocumentsGetAllResponses, EmbedEmbedPostData, EmbedEmbedPostErrors, EmbedEmbedPostResponses, JobsCreateJobData, JobsCreateJobErrors, JobsCreateJobResponses, JobsDeleteJobData, JobsDeleteJobErrors, JobsDeleteJobResponses, JobsGetJobData, JobsGetJobErrors, JobsGetJobResponses, JobsListJobsData, JobsListJobsErrors, JobsListJobsResponses, JobsUpdateJobData, JobsUpdateJobErrors, JobsUpdateJobResponses, MetadataCreateData, MetadataCreateErrors, MetadataCreateResponses, MetadataDeleteData, MetadataDeleteErrors, MetadataDeleteResponses, MetadataGetBySourceData, MetadataGetBySourceErrors, MetadataGetBySourceResponses, MetadataProbeData, MetadataProbeErrors, MetadataProbeResponses, MetadataUpdateData, MetadataUpdateErrors, MetadataUpdateResponses, OntologyGetAnnotationsForDocumentData, OntologyGetAnnotationsForDocumentErrors, OntologyGetAnnotationsForDocumentResponses, OntologyGetData, OntologyGetErrors, OntologyGetNodePathData, OntologyGetNodePathErrors, OntologyGetNodePathResponses, OntologyGetPotentialMappingsData, OntologyGetPotentialMappingsErrors, OntologyGetPotentialMappingsResponses, OntologyGetResponses, OntologyNameExistsData, OntologyNameExistsErrors, OntologyNameExistsResponses, PrecomputedStatsGetByNameData, PrecomputedStatsGetByNameErrors, PrecomputedStatsGetByNameResponses, SearchAnnotationsData, SearchAnnotationsErrors, SearchAnnotationsResponses, SearchDocumentsData, SearchDocumentsErrors, SearchDocumentsResponses, SearchHumanizeData, SearchHumanizeErrors, SearchHumanizeResponses, SearchTopicsData, SearchTopicsErrors, SearchTopicsResponses, TopicsGetTopicData, TopicsGetTopicErrors, TopicsGetTopicResponses, UpdateOntologyEntryData, UpdateOntologyEntryErrors, UpdateOntologyEntryResponses } from './types.gen';
import { zAddOntologyEntryBody, zDeleteOntologyEntryPath, zDocumentsGetAllQuery, zDocumentsGetAllResponse, zEmbedEmbedPostBody, zJobsCreateJobBody, zJobsCreateJobResponse, zJobsDeleteJobPath, zJobsDeleteJobResponse, zJobsGetJobPath, zJobsGetJobResponse, zJobsListJobsResponse, zJobsUpdateJobBody, zJobsUpdateJobResponse, zMetadataCreateBody, zMetadataDeletePath, zMetadataDeleteResponse, zMetadataGetBySourceResponse, zMetadataProbeResponse, zMetadataUpdateBody, zMetadataUpdateResponse, zOntologyGetAnnotationsForDocumentPath, zOntologyGetAnnotationsForDocumentResponse, zOntologyGetNodePathPath, zOntologyGetNodePathResponse, zOntologyGetPotentialMappingsResponse, zOntologyGetResponse, zOntologyNameExistsPath, zOntologyNameExistsResponse, zPrecomputedStatsGetByNamePath, zPrecomputedStatsGetByNameResponse, zSearchAnnotationsBody, zSearchAnnotationsResponse, zSearchDocumentsBody, zSearchDocumentsResponse, zSearchHumanizeBody, zSearchHumanizeResponse, zSearchTopicsBody, zSearchTopicsResponse, zTopicsGetTopicPath, zTopicsGetTopicResponse, zUpdateOntologyEntryBody } from './zod.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

class HeyApiClient {
    protected client: Client;
    
    constructor(args?: {
        client?: Client;
    }) {
        this.client = args?.client ?? client;
    }
}

class HeyApiRegistry<T> {
    private readonly defaultKey = 'default';
    
    private readonly instances: Map<string, T> = new Map();
    
    get(key?: string): T {
        const instance = this.instances.get(key ?? this.defaultKey);
        if (!instance) {
            throw new Error(`No SDK client found. Create one with "new ApiClient()" to fix this error.`);
        }
        return instance;
    }
    
    set(value: T, key?: string): void {
        this.instances.set(key ?? this.defaultKey, value);
    }
}

export class ApiClient extends HeyApiClient {
    public static readonly __registry: HeyApiRegistry<ApiClient> = new HeyApiRegistry<ApiClient>();
    
    constructor(args?: {
        client?: Client;
        key?: string;
    }) {
        super(args);
        ApiClient.__registry.set(this, args?.key);
    }
    
    /**
     * Delete Job
     */
    public jobsDeleteJob<ThrowOnError extends boolean = false>(options: Options<JobsDeleteJobData, ThrowOnError>): RequestResult<JobsDeleteJobResponses, JobsDeleteJobErrors, ThrowOnError> {
        return (options.client ?? this.client).delete<JobsDeleteJobResponses, JobsDeleteJobErrors, ThrowOnError>({
            requestValidator: async (data) => await z.object({
                body: z.never().optional(),
                path: zJobsDeleteJobPath,
                query: z.never().optional()
            }).parseAsync(data),
            responseValidator: async (data) => await zJobsDeleteJobResponse.parseAsync(data),
            url: '/job/id/{job_id}',
            ...options
        });
    }
    
    /**
     * Get Job
     */
    public jobsGetJob<ThrowOnError extends boolean = false>(options: Options<JobsGetJobData, ThrowOnError>): RequestResult<JobsGetJobResponses, JobsGetJobErrors, ThrowOnError> {
        return (options.client ?? this.client).get<JobsGetJobResponses, JobsGetJobErrors, ThrowOnError>({
            requestValidator: async (data) => await z.object({
                body: z.never().optional(),
                path: zJobsGetJobPath,
                query: z.never().optional()
            }).parseAsync(data),
            responseValidator: async (data) => await zJobsGetJobResponse.parseAsync(data),
            url: '/job/id/{job_id}',
            ...options
        });
    }
    
    /**
     * List Jobs
     */
    public jobsListJobs<ThrowOnError extends boolean = false>(options?: Options<JobsListJobsData, ThrowOnError>): RequestResult<JobsListJobsResponses, JobsListJobsErrors, ThrowOnError> {
        return (options?.client ?? this.client).get<JobsListJobsResponses, JobsListJobsErrors, ThrowOnError>({
            requestValidator: async (data) => await z.object({
                body: z.never().optional(),
                path: z.never().optional(),
                query: z.never().optional()
            }).parseAsync(data),
            responseValidator: async (data) => await zJobsListJobsResponse.parseAsync(data),
            url: '/job',
            ...options
        });
    }
    
    /**
     * Create Job
     */
    public jobsCreateJob<ThrowOnError extends boolean = false>(options: Options<JobsCreateJobData, ThrowOnError>): RequestResult<JobsCreateJobResponses, JobsCreateJobErrors, ThrowOnError> {
        return (options.client ?? this.client).post<JobsCreateJobResponses, JobsCreateJobErrors, ThrowOnError>({
            requestValidator: async (data) => await z.object({
                body: zJobsCreateJobBody,
                path: z.never().optional(),
                query: z.never().optional()
            }).parseAsync(data),
            responseValidator: async (data) => await zJobsCreateJobResponse.parseAsync(data),
            url: '/job',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    /**
     * Update Job
     */
    public jobsUpdateJob<ThrowOnError extends boolean = false>(options: Options<JobsUpdateJobData, ThrowOnError>): RequestResult<JobsUpdateJobResponses, JobsUpdateJobErrors, ThrowOnError> {
        return (options.client ?? this.client).put<JobsUpdateJobResponses, JobsUpdateJobErrors, ThrowOnError>({
            requestValidator: async (data) => await z.object({
                body: zJobsUpdateJobBody,
                path: z.never().optional(),
                query: z.never().optional()
            }).parseAsync(data),
            responseValidator: async (data) => await zJobsUpdateJobResponse.parseAsync(data),
            url: '/job',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    /**
     * Get Topic
     */
    public topicsGetTopic<ThrowOnError extends boolean = false>(options: Options<TopicsGetTopicData, ThrowOnError>): RequestResult<TopicsGetTopicResponses, TopicsGetTopicErrors, ThrowOnError> {
        return (options.client ?? this.client).get<TopicsGetTopicResponses, TopicsGetTopicErrors, ThrowOnError>({
            requestValidator: async (data) => await z.object({
                body: z.never().optional(),
                path: zTopicsGetTopicPath,
                query: z.never().optional()
            }).parseAsync(data),
            responseValidator: async (data) => await zTopicsGetTopicResponse.parseAsync(data),
            url: '/topics/{topic_id}',
            ...options
        });
    }
    
    /**
     * Embed
     */
    public embedEmbedPost<ThrowOnError extends boolean = false>(options: Options<EmbedEmbedPostData, ThrowOnError>): RequestResult<EmbedEmbedPostResponses, EmbedEmbedPostErrors, ThrowOnError> {
        return (options.client ?? this.client).post<EmbedEmbedPostResponses, EmbedEmbedPostErrors, ThrowOnError>({
            requestValidator: async (data) => await z.object({
                body: zEmbedEmbedPostBody,
                path: z.never().optional(),
                query: z.never().optional()
            }).parseAsync(data),
            url: '/embed/',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    /**
     * List Documents
     */
    public documentsGetAll<ThrowOnError extends boolean = false>(options?: Options<DocumentsGetAllData, ThrowOnError>): RequestResult<DocumentsGetAllResponses, DocumentsGetAllErrors, ThrowOnError> {
        return (options?.client ?? this.client).get<DocumentsGetAllResponses, DocumentsGetAllErrors, ThrowOnError>({
            requestValidator: async (data) => await z.object({
                body: z.never().optional(),
                path: z.never().optional(),
                query: zDocumentsGetAllQuery.optional()
            }).parseAsync(data),
            responseValidator: async (data) => await zDocumentsGetAllResponse.parseAsync(data),
            url: '/doc',
            ...options
        });
    }
    
    /**
     * Get Ontology
     */
    public ontologyGet<ThrowOnError extends boolean = false>(options?: Options<OntologyGetData, ThrowOnError>): RequestResult<OntologyGetResponses, OntologyGetErrors, ThrowOnError> {
        return (options?.client ?? this.client).get<OntologyGetResponses, OntologyGetErrors, ThrowOnError>({
            requestValidator: async (data) => await z.object({
                body: z.never().optional(),
                path: z.never().optional(),
                query: z.never().optional()
            }).parseAsync(data),
            responseValidator: async (data) => await zOntologyGetResponse.parseAsync(data),
            url: '/ontology',
            ...options
        });
    }
    
    /**
     * Add Ontology Entry
     */
    public addOntologyEntry<ThrowOnError extends boolean = false>(options: Options<AddOntologyEntryData, ThrowOnError>): RequestResult<AddOntologyEntryResponses, AddOntologyEntryErrors, ThrowOnError> {
        return (options.client ?? this.client).post<AddOntologyEntryResponses, AddOntologyEntryErrors, ThrowOnError>({
            requestValidator: async (data) => await z.object({
                body: zAddOntologyEntryBody,
                path: z.never().optional(),
                query: z.never().optional()
            }).parseAsync(data),
            url: '/ontology',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    /**
     * Name Exists
     */
    public ontologyNameExists<ThrowOnError extends boolean = false>(options: Options<OntologyNameExistsData, ThrowOnError>): RequestResult<OntologyNameExistsResponses, OntologyNameExistsErrors, ThrowOnError> {
        return (options.client ?? this.client).get<OntologyNameExistsResponses, OntologyNameExistsErrors, ThrowOnError>({
            requestValidator: async (data) => await z.object({
                body: z.never().optional(),
                path: zOntologyNameExistsPath,
                query: z.never().optional()
            }).parseAsync(data),
            responseValidator: async (data) => await zOntologyNameExistsResponse.parseAsync(data),
            url: '/ontology/exists/{name}',
            ...options
        });
    }
    
    /**
     * Get Annotations For Doc
     */
    public ontologyGetAnnotationsForDocument<ThrowOnError extends boolean = false>(options: Options<OntologyGetAnnotationsForDocumentData, ThrowOnError>): RequestResult<OntologyGetAnnotationsForDocumentResponses, OntologyGetAnnotationsForDocumentErrors, ThrowOnError> {
        return (options.client ?? this.client).get<OntologyGetAnnotationsForDocumentResponses, OntologyGetAnnotationsForDocumentErrors, ThrowOnError>({
            requestValidator: async (data) => await z.object({
                body: z.never().optional(),
                path: zOntologyGetAnnotationsForDocumentPath,
                query: z.never().optional()
            }).parseAsync(data),
            responseValidator: async (data) => await zOntologyGetAnnotationsForDocumentResponse.parseAsync(data),
            url: '/ontology/document/{doc_id}',
            ...options
        });
    }
    
    /**
     * Update Entry
     */
    public updateOntologyEntry<ThrowOnError extends boolean = false>(options: Options<UpdateOntologyEntryData, ThrowOnError>): RequestResult<UpdateOntologyEntryResponses, UpdateOntologyEntryErrors, ThrowOnError> {
        return (options.client ?? this.client).post<UpdateOntologyEntryResponses, UpdateOntologyEntryErrors, ThrowOnError>({
            requestValidator: async (data) => await z.object({
                body: zUpdateOntologyEntryBody,
                path: z.never().optional(),
                query: z.never().optional()
            }).parseAsync(data),
            url: '/ontology/update',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    /**
     * Delete Entry
     */
    public deleteOntologyEntry<ThrowOnError extends boolean = false>(options: Options<DeleteOntologyEntryData, ThrowOnError>): RequestResult<DeleteOntologyEntryResponses, DeleteOntologyEntryErrors, ThrowOnError> {
        return (options.client ?? this.client).delete<DeleteOntologyEntryResponses, DeleteOntologyEntryErrors, ThrowOnError>({
            requestValidator: async (data) => await z.object({
                body: z.never().optional(),
                path: zDeleteOntologyEntryPath,
                query: z.never().optional()
            }).parseAsync(data),
            url: '/ontology/node/{node_id}',
            ...options
        });
    }
    
    /**
     * Get Node Path
     */
    public ontologyGetNodePath<ThrowOnError extends boolean = false>(options: Options<OntologyGetNodePathData, ThrowOnError>): RequestResult<OntologyGetNodePathResponses, OntologyGetNodePathErrors, ThrowOnError> {
        return (options.client ?? this.client).get<OntologyGetNodePathResponses, OntologyGetNodePathErrors, ThrowOnError>({
            requestValidator: async (data) => await z.object({
                body: z.never().optional(),
                path: zOntologyGetNodePathPath,
                query: z.never().optional()
            }).parseAsync(data),
            responseValidator: async (data) => await zOntologyGetNodePathResponse.parseAsync(data),
            url: '/ontology/node/{path}/path',
            ...options
        });
    }
    
    /**
     * Get Potential Mappings
     */
    public ontologyGetPotentialMappings<ThrowOnError extends boolean = false>(options?: Options<OntologyGetPotentialMappingsData, ThrowOnError>): RequestResult<OntologyGetPotentialMappingsResponses, OntologyGetPotentialMappingsErrors, ThrowOnError> {
        return (options?.client ?? this.client).get<OntologyGetPotentialMappingsResponses, OntologyGetPotentialMappingsErrors, ThrowOnError>({
            requestValidator: async (data) => await z.object({
                body: z.never().optional(),
                path: z.never().optional(),
                query: z.never().optional()
            }).parseAsync(data),
            responseValidator: async (data) => await zOntologyGetPotentialMappingsResponse.parseAsync(data),
            url: '/ontology/potential_mappings',
            ...options
        });
    }
    
    /**
     * Metadata Create
     */
    public metadataCreate<ThrowOnError extends boolean = false>(options: Options<MetadataCreateData, ThrowOnError>): RequestResult<MetadataCreateResponses, MetadataCreateErrors, ThrowOnError> {
        return (options.client ?? this.client).post<MetadataCreateResponses, MetadataCreateErrors, ThrowOnError>({
            requestValidator: async (data) => await z.object({
                body: zMetadataCreateBody,
                path: z.never().optional(),
                query: z.never().optional()
            }).parseAsync(data),
            url: '/metadata/',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    /**
     * Get All By Source
     */
    public metadataGetBySource<ThrowOnError extends boolean = false>(options?: Options<MetadataGetBySourceData, ThrowOnError>): RequestResult<MetadataGetBySourceResponses, MetadataGetBySourceErrors, ThrowOnError> {
        return (options?.client ?? this.client).get<MetadataGetBySourceResponses, MetadataGetBySourceErrors, ThrowOnError>({
            requestValidator: async (data) => await z.object({
                body: z.never().optional(),
                path: z.never().optional(),
                query: z.never().optional()
            }).parseAsync(data),
            responseValidator: async (data) => await zMetadataGetBySourceResponse.parseAsync(data),
            url: '/metadata',
            ...options
        });
    }
    
    /**
     * Get Available
     */
    public metadataProbe<ThrowOnError extends boolean = false>(options?: Options<MetadataProbeData, ThrowOnError>): RequestResult<MetadataProbeResponses, MetadataProbeErrors, ThrowOnError> {
        return (options?.client ?? this.client).get<MetadataProbeResponses, MetadataProbeErrors, ThrowOnError>({
            requestValidator: async (data) => await z.object({
                body: z.never().optional(),
                path: z.never().optional(),
                query: z.never().optional()
            }).parseAsync(data),
            responseValidator: async (data) => await zMetadataProbeResponse.parseAsync(data),
            url: '/metadata/probe',
            ...options
        });
    }
    
    /**
     * Metadata Delete
     */
    public metadataDelete<ThrowOnError extends boolean = false>(options: Options<MetadataDeleteData, ThrowOnError>): RequestResult<MetadataDeleteResponses, MetadataDeleteErrors, ThrowOnError> {
        return (options.client ?? this.client).delete<MetadataDeleteResponses, MetadataDeleteErrors, ThrowOnError>({
            requestValidator: async (data) => await z.object({
                body: z.never().optional(),
                path: zMetadataDeletePath,
                query: z.never().optional()
            }).parseAsync(data),
            responseValidator: async (data) => await zMetadataDeleteResponse.parseAsync(data),
            url: '/metadata/{metadata_id}',
            ...options
        });
    }
    
    /**
     * Metadata Update
     */
    public metadataUpdate<ThrowOnError extends boolean = false>(options: Options<MetadataUpdateData, ThrowOnError>): RequestResult<MetadataUpdateResponses, MetadataUpdateErrors, ThrowOnError> {
        return (options.client ?? this.client).put<MetadataUpdateResponses, MetadataUpdateErrors, ThrowOnError>({
            requestValidator: async (data) => await z.object({
                body: zMetadataUpdateBody,
                path: z.never().optional(),
                query: z.never().optional()
            }).parseAsync(data),
            responseValidator: async (data) => await zMetadataUpdateResponse.parseAsync(data),
            url: '/metadata/{metadata_id}',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    /**
     * Get By Name
     */
    public precomputedStatsGetByName<ThrowOnError extends boolean = false>(options: Options<PrecomputedStatsGetByNameData, ThrowOnError>): RequestResult<PrecomputedStatsGetByNameResponses, PrecomputedStatsGetByNameErrors, ThrowOnError> {
        return (options.client ?? this.client).get<PrecomputedStatsGetByNameResponses, PrecomputedStatsGetByNameErrors, ThrowOnError>({
            requestValidator: async (data) => await z.object({
                body: z.never().optional(),
                path: zPrecomputedStatsGetByNamePath,
                query: z.never().optional()
            }).parseAsync(data),
            responseValidator: async (data) => await zPrecomputedStatsGetByNameResponse.parseAsync(data),
            url: '/stats/{name}',
            ...options
        });
    }
    
    /**
     * Humanize Query
     */
    public searchHumanize<ThrowOnError extends boolean = false>(options: Options<SearchHumanizeData, ThrowOnError>): RequestResult<SearchHumanizeResponses, SearchHumanizeErrors, ThrowOnError> {
        return (options.client ?? this.client).post<SearchHumanizeResponses, SearchHumanizeErrors, ThrowOnError>({
            requestValidator: async (data) => await z.object({
                body: zSearchHumanizeBody,
                path: z.never().optional(),
                query: z.never().optional()
            }).parseAsync(data),
            responseValidator: async (data) => await zSearchHumanizeResponse.parseAsync(data),
            url: '/search/humanize',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    /**
     * Search Documents
     */
    public searchDocuments<ThrowOnError extends boolean = false>(options: Options<SearchDocumentsData, ThrowOnError>): RequestResult<SearchDocumentsResponses, SearchDocumentsErrors, ThrowOnError> {
        return (options.client ?? this.client).post<SearchDocumentsResponses, SearchDocumentsErrors, ThrowOnError>({
            requestValidator: async (data) => await z.object({
                body: zSearchDocumentsBody,
                path: z.never().optional(),
                query: z.never().optional()
            }).parseAsync(data),
            responseValidator: async (data) => await zSearchDocumentsResponse.parseAsync(data),
            url: '/search/docs',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    /**
     * Search Topics
     */
    public searchTopics<ThrowOnError extends boolean = false>(options: Options<SearchTopicsData, ThrowOnError>): RequestResult<SearchTopicsResponses, SearchTopicsErrors, ThrowOnError> {
        return (options.client ?? this.client).post<SearchTopicsResponses, SearchTopicsErrors, ThrowOnError>({
            requestValidator: async (data) => await z.object({
                body: zSearchTopicsBody,
                path: z.never().optional(),
                query: z.never().optional()
            }).parseAsync(data),
            responseValidator: async (data) => await zSearchTopicsResponse.parseAsync(data),
            url: '/search/topics',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    /**
     * Search Annotations
     */
    public searchAnnotations<ThrowOnError extends boolean = false>(options: Options<SearchAnnotationsData, ThrowOnError>): RequestResult<SearchAnnotationsResponses, SearchAnnotationsErrors, ThrowOnError> {
        return (options.client ?? this.client).post<SearchAnnotationsResponses, SearchAnnotationsErrors, ThrowOnError>({
            requestValidator: async (data) => await z.object({
                body: zSearchAnnotationsBody,
                path: z.never().optional(),
                query: z.never().optional()
            }).parseAsync(data),
            responseValidator: async (data) => await zSearchAnnotationsResponse.parseAsync(data),
            url: '/search/annotations',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
}
