// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:8003' | (string & {});
};

/**
 * AnnotationDocResult
 */
export type AnnotationDocResult = {
    /**
     * Document Id
     */
    document_id: string;
    /**
     * Document Title
     */
    document_title: string;
    /**
     * Highlights
     */
    highlights: Array<AnnotationHighlight>;
};

/**
 * AnnotationHighlight
 */
export type AnnotationHighlight = {
    /**
     * Id
     */
    id: string;
    /**
     * Sentence Id
     */
    sentence_id: string;
    /**
     * Annotation
     */
    annotation: string;
    /**
     * Sentence
     */
    sentence: string;
};

/**
 * AnnotationIdOntologyMapping
 */
export type AnnotationIdOntologyMapping = {
    /**
     * Annotation Id
     */
    annotation_id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Path
     */
    path: string;
    /**
     * Color
     */
    color: string;
};

/**
 * AnnotationOntologyMappingList
 */
export type AnnotationOntologyMappingList = {
    /**
     * Mapping
     */
    mapping: {
        [key: string]: AnnotationIdOntologyMapping;
    };
};

/**
 * AnnotationSearchResult
 */
export type AnnotationSearchResult = {
    /**
     * Name
     */
    name: string;
    /**
     * Path
     */
    path: string;
    /**
     * Docs
     */
    docs: Array<AnnotationDocResult>;
};

/**
 * AnnotationSearchResults
 */
export type AnnotationSearchResults = {
    /**
     * Next Cursor
     */
    next_cursor: number | null;
    /**
     * Results
     */
    results: Array<AnnotationSearchResult>;
    /**
     * Total
     */
    total: number;
};

/**
 * AuthedUser
 */
export type AuthedUser = {
    /**
     * User Id
     */
    user_id: string;
    /**
     * Role
     */
    role: string;
    /**
     * Permissions
     */
    permissions?: {
        [key: string]: Array<string>;
    };
};

/**
 * Body_embed_embed__post
 */
export type BodyEmbedEmbedPost = {
    request: EmbeddingRequest;
    user: AuthedUser;
};

/**
 * DataType
 */
export type DataType = 'string' | 'string_array' | 'int' | 'float' | 'boolean' | 'date';

/**
 * Document
 */
export type Document = {
    text: Text;
    /**
     * Title
     */
    title: string;
    /**
     * Id
     */
    id: string;
    /**
     * Metadata Json
     */
    metadata_json?: {
        [key: string]: unknown;
    };
};

/**
 * DocumentHighlight
 */
export type DocumentHighlight = {
    /**
     * Document Id
     */
    document_id: string;
    /**
     * Sentence Id
     */
    sentence_id: string;
    /**
     * Text
     */
    text: string;
};

/**
 * DocumentInfo
 */
export type DocumentInfo = {
    /**
     * Id
     */
    id: string;
    /**
     * Title
     */
    title: string;
    /**
     * Snippet
     */
    snippet: string;
};

/**
 * DocumentListResponse
 */
export type DocumentListResponse = {
    /**
     * Items
     */
    items: Array<DocumentInfo>;
    /**
     * Total
     */
    total?: number;
    /**
     * Total Pages
     */
    total_pages?: number;
    /**
     * Next Cursor
     */
    next_cursor?: number | unknown;
    /**
     * Previous Cursor
     */
    previous_cursor?: number | unknown;
};

/**
 * DocumentSearchResult
 */
export type DocumentSearchResult = {
    /**
     * Document Id
     */
    document_id: string;
    /**
     * Document Title
     */
    document_title: string;
    /**
     * Highlights
     */
    highlights: Array<DocumentHighlight>;
};

/**
 * DocumentSearchResults
 */
export type DocumentSearchResults = {
    /**
     * Next Cursor
     */
    next_cursor: number | null;
    /**
     * Results
     */
    results: Array<DocumentSearchResult>;
    /**
     * Total
     */
    total: number;
};

/**
 * EmbeddingRequest
 */
export type EmbeddingRequest = {
    /**
     * Text
     */
    text: string;
};

/**
 * ErrorDetail
 */
export type ErrorDetail = {
    /**
     * Detail
     */
    detail: string;
    /**
     * Code
     */
    code: number;
};

/**
 * File
 */
export type File = {
    /**
     * Path
     */
    path?: string | unknown;
    /**
     * Docid
     */
    docId?: string | unknown;
    /**
     * Mime Type
     */
    mime_type?: string;
    /**
     * Encoding
     */
    encoding?: string | unknown;
    /**
     * Content
     */
    content: string;
    /**
     * Metadata
     */
    metadata?: {
        [key: string]: unknown;
    };
};

/**
 * GlobalMetadata
 */
export type GlobalMetadataInput = {
    /**
     * Id
     */
    id?: string | null;
    source: MetadataSource;
    /**
     * Name
     */
    name: string;
    data_type: DataType;
    /**
     * Formatter
     */
    formatter?: string | null;
    /**
     * Links To Document Id
     */
    links_to_document_id?: boolean;
    /**
     * Links To Metadata Id
     */
    links_to_metadata_id?: string | null;
    linked_to?: GlobalMetadataInput | unknown;
};

/**
 * GlobalMetadata
 */
export type GlobalMetadataOutput = {
    /**
     * Id
     */
    id?: string | null;
    source: MetadataSource;
    /**
     * Name
     */
    name: string;
    data_type: DataType;
    /**
     * Formatter
     */
    formatter?: string | null;
    /**
     * Links To Document Id
     */
    links_to_document_id?: boolean;
    /**
     * Links To Metadata Id
     */
    links_to_metadata_id?: string | null;
    linked_to?: GlobalMetadataOutput | unknown;
};

/**
 * GlobalMetadataAvailable
 */
export type GlobalMetadataAvailable = {
    /**
     * Source
     */
    source: string;
    /**
     * Key
     */
    key: string;
};

/**
 * GlobalMetadataAvailableList
 */
export type GlobalMetadataAvailableList = Array<GlobalMetadataAvailable>;

/**
 * GlobalMetadataBySource
 */
export type GlobalMetadataBySource = {
    /**
     * Documents
     */
    documents: {
        [key: string]: GlobalMetadataLinkedSource;
    };
    /**
     * Annotations
     */
    annotations: {
        [key: string]: GlobalMetadataLinkedSource;
    };
    /**
     * Sentences
     */
    sentences: {
        [key: string]: GlobalMetadataLinkedSource;
    };
};

/**
 * GlobalMetadataLinkedSource
 */
export type GlobalMetadataLinkedSource = {
    /**
     * Id
     */
    id: string;
    source: MetadataSource;
    /**
     * Name
     */
    name: string;
    data_type: DataType;
    /**
     * Formatter
     */
    formatter?: string | null;
    /**
     * Links To Document Id
     */
    links_to_document_id?: boolean;
    /**
     * Links To Metadata Id
     */
    links_to_metadata_id?: string | null;
    linked_to?: GlobalMetadataOutput | unknown;
    /**
     * Linked Name
     */
    linked_name?: string | null;
    linked_source?: MetadataSource | unknown;
};

/**
 * GlobalMetadataUpdate
 */
export type GlobalMetadataUpdate = {
    /**
     * Id
     */
    id: string;
    source?: MetadataSource | unknown;
    /**
     * Name
     */
    name?: string | unknown;
    data_type?: DataType | unknown;
    /**
     * Formatter
     */
    formatter?: string | unknown;
    /**
     * Links To Document Id
     */
    links_to_document_id?: boolean;
    /**
     * Links To Metadata Id
     */
    links_to_metadata_id?: string | unknown;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * HumanizedQuery
 */
export type HumanizedQuery = {
    /**
     * Annotations
     */
    annotations: Array<string>;
    /**
     * Topics
     */
    topics: Array<string>;
};

/**
 * IsolatedOntologyEntry
 */
export type IsolatedOntologyEntry = {
    /**
     * Id
     */
    id?: number | null;
    /**
     * Name
     */
    name: string;
    /**
     * Path
     */
    path: string;
    /**
     * Description
     */
    description: string;
    /**
     * Color
     */
    color: string;
    /**
     * Parent Id
     */
    parent_id?: number | null;
    /**
     * Mappings
     */
    mappings?: Array<OntologyMapping>;
    /**
     * Properties
     */
    properties?: {
        [key: string]: OntologyProperty;
    };
};

/**
 * Job
 */
export type Job = {
    /**
     * Id
     */
    id: number;
    /**
     * Name
     */
    name: string;
    status: JobStatus;
    type_: JobType;
    /**
     * User Id
     */
    user_id: string;
    /**
     * Total
     */
    total: number;
    /**
     * Completed
     */
    completed: number;
    /**
     * Failed
     */
    failed: number;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Started At
     */
    started_at?: string | null;
    /**
     * Completed At
     */
    completed_at?: string | null;
    /**
     * Metadata Json
     */
    metadata_json?: {
        [key: string]: unknown;
    };
    /**
     * Deleting
     */
    deleting?: boolean;
};

/**
 * JobAnnotateRequest
 */
export type JobAnnotateRequest = {
    /**
     * Id
     */
    id: number;
    /**
     * Files
     */
    files: Array<File>;
    /**
     * Complete
     */
    complete?: boolean;
};

/**
 * JobCreateRequest
 */
export type JobCreateRequest = {
    /**
     * Name
     */
    name: string;
    type_: JobType;
    /**
     * Total
     */
    total?: number;
    status?: JobStatus | unknown;
    /**
     * Metadata Json
     */
    metadata_json?: {
        [key: string]: unknown;
    };
};

/**
 * JobListResponse
 */
export type JobListResponse = Array<Job>;

/**
 * JobStatus
 */
export type JobStatus = 'waiting' | 'running' | 'completed' | 'cancelled' | 'failed';

/**
 * JobType
 */
export type JobType = 'annotation' | 'update' | 'analyticsupdate' | 'other';

/**
 * JobUpdateRequest
 */
export type JobUpdateRequest = {
    /**
     * Id
     */
    id: number;
    status?: JobStatus | unknown;
    /**
     * Total
     */
    total?: number;
    /**
     * Completed
     */
    completed?: number;
    /**
     * Failed
     */
    failed?: number;
    /**
     * Metadata Json
     */
    metadata_json?: {
        [key: string]: unknown;
    } | unknown;
};

/**
 * MetadataSource
 */
export type MetadataSource = 'document' | 'annotation' | 'sentence';

export type NumpyArray = Array<number>;

/**
 * OntologyEntryCreationRequest
 */
export type OntologyEntryCreationRequest = {
    /**
     * Parent Id
     */
    parent_id: number;
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description?: string | null;
};

/**
 * OntologyFrontEnd
 */
export type OntologyFrontEnd = {
    /**
     * Paths
     */
    paths: Array<string>;
    /**
     * Nodes
     */
    nodes: {
        [key: string]: IsolatedOntologyEntry;
    };
};

/**
 * OntologyMapping
 */
export type OntologyMapping = {
    /**
     * Id
     */
    id?: number | null;
    /**
     * Mapping
     */
    mapping: string;
};

/**
 * OntologyNameExists
 */
export type OntologyNameExists = {
    /**
     * Exists
     */
    exists: boolean;
};

/**
 * OntologyPaths
 */
export type OntologyPaths = Array<string>;

/**
 * OntologyProperty
 */
export type OntologyProperty = {
    /**
     * Value
     */
    value: string | boolean | number | number | Array<string>;
    /**
     * Datatype
     */
    dataType: 'string' | 'boolean' | 'number' | 'metadata';
    /**
     * Inherit
     */
    inherit?: boolean;
    /**
     * Display
     */
    display?: boolean;
    /**
     * Definedby
     */
    definedBy?: string | null;
};

/**
 * OntologyUpdateRequest
 */
export type OntologyUpdateRequest = {
    /**
     * Id
     */
    id: number;
    /**
     * Color
     */
    color?: string | unknown;
    /**
     * Description
     */
    description?: string | unknown;
    /**
     * Properties
     */
    properties?: {
        [key: string]: OntologyProperty;
    } | unknown;
    /**
     * Mapping
     */
    mapping?: Array<string> | unknown;
};

/**
 * PotentialMappingList
 */
export type PotentialMappingList = {
    /**
     * Items
     */
    items: {
        [key: string]: string | unknown;
    };
};

/**
 * PreComputedStats
 */
export type PreComputedStats = {
    /**
     * Id
     */
    id?: number | null;
    /**
     * Name
     */
    name: string;
    /**
     * Value
     */
    value?: {
        [key: string]: unknown;
    };
};

/**
 * SearchParams
 */
export type SearchParams = {
    /**
     * Cursor
     */
    cursor?: number | null;
    /**
     * Limit
     */
    limit?: number;
    /**
     * Q
     */
    q?: string | null;
    /**
     * Aid
     */
    aid?: Array<string> | null;
    /**
     * Sid
     */
    sid?: Array<string> | null;
    /**
     * Tid
     */
    tid?: Array<number> | null;
    /**
     * Is Strict
     */
    is_strict: boolean;
};

/**
 * Text
 */
export type Text = {
    /**
     * Id
     */
    id?: string;
    /**
     * Start
     */
    start: number;
    /**
     * End
     */
    end: number;
    /**
     * Content
     */
    content: string;
    /**
     * Document Id
     */
    document_id: string;
    /**
     * Metadata Json
     */
    metadata_json?: {
        [key: string]: unknown;
    };
    embedding?: NumpyArray;
    /**
     * Annotations
     */
    annotations?: Array<TextAnnotation>;
};

/**
 * TextAnnotation
 */
export type TextAnnotation = {
    /**
     * Id
     */
    id?: string;
    /**
     * Start
     */
    start: number;
    /**
     * End
     */
    end: number;
    /**
     * Content
     */
    content: string;
    /**
     * Document Id
     */
    document_id: string;
    /**
     * Metadata Json
     */
    metadata_json?: {
        [key: string]: unknown;
    };
    /**
     * Sentence Index
     */
    sentence_index: number;
    /**
     * Type
     */
    type_: string;
    /**
     * Value
     */
    value: string;
    /**
     * Source
     */
    source: string;
    embedding?: NumpyArray;
};

/**
 * TopicDocSearchResult
 */
export type TopicDocSearchResult = {
    /**
     * Document Id
     */
    document_id: string;
    /**
     * Document Title
     */
    document_title: string;
    /**
     * Highlights
     */
    highlights: Array<TopicHighlight>;
};

/**
 * TopicEntity
 */
export type TopicEntity = {
    /**
     * Entity
     */
    entity: string;
    /**
     * Type
     */
    type: string;
    /**
     * Count
     */
    count: number;
};

/**
 * TopicFrontendResult
 */
export type TopicFrontendResult = {
    /**
     * Id
     */
    id: number;
    /**
     * Name
     */
    name: string;
    /**
     * Is Fixed
     */
    is_fixed: boolean;
    /**
     * Sentence Count
     */
    sentence_count: number;
    /**
     * Document Count
     */
    document_count: number;
    /**
     * Sentences
     */
    sentences: Array<TopicSimilarSentence>;
    /**
     * Entities
     */
    entities: Array<TopicEntity>;
    /**
     * Keywords
     */
    keywords: Array<string>;
};

/**
 * TopicGraph
 */
export type TopicGraph = {
    /**
     * Nodes
     */
    nodes: Array<TopicNode>;
    /**
     * Similarities
     */
    similarities: Array<TopicSimilarity>;
};

/**
 * TopicHighlight
 */
export type TopicHighlight = {
    /**
     * Sentence Id
     */
    sentence_id: string;
    /**
     * Text
     */
    text: string;
};

/**
 * TopicNode
 */
export type TopicNode = {
    /**
     * Id
     */
    id: string;
    /**
     * Text
     */
    text: string;
    /**
     * Display
     */
    display: string;
    /**
     * Value
     */
    value: number;
    /**
     * Type
     */
    type: 'topic' | 'concept';
    /**
     * Subvalues
     */
    subvalues: {
        [key: string]: number;
    };
};

/**
 * TopicSearchResult
 */
export type TopicSearchResult = {
    /**
     * Id
     */
    id: number;
    /**
     * Name
     */
    name: string;
    /**
     * Docs
     */
    docs: Array<TopicDocSearchResult>;
};

/**
 * TopicSearchResults
 */
export type TopicSearchResults = {
    /**
     * Next Cursor
     */
    next_cursor: number | null;
    /**
     * Results
     */
    results: Array<TopicSearchResult>;
    /**
     * Total
     */
    total: number;
};

/**
 * TopicSimilarSentence
 */
export type TopicSimilarSentence = {
    /**
     * Sentence Id
     */
    sentence_id: string;
    /**
     * Document Id
     */
    document_id: string;
    /**
     * Similarity
     */
    similarity: number;
    /**
     * Content
     */
    content: string;
};

/**
 * TopicSimilarity
 */
export type TopicSimilarity = {
    /**
     * Id1
     */
    id1: string;
    /**
     * Id2
     */
    id2: string;
    /**
     * Similarity
     */
    similarity: number;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

export type JobsDeleteJobData = {
    body?: never;
    path: {
        /**
         * Job Id
         */
        job_id: number;
    };
    query?: never;
    url: '/job/id/{job_id}';
};

export type JobsDeleteJobErrors = {
    /**
     * Bad Request
     */
    400: ErrorDetail;
    /**
     * Unauthorized
     */
    401: ErrorDetail;
    /**
     * Not Found
     */
    404: ErrorDetail;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type JobsDeleteJobError = JobsDeleteJobErrors[keyof JobsDeleteJobErrors];

export type JobsDeleteJobResponses = {
    /**
     * Successful Response
     */
    200: Job;
};

export type JobsDeleteJobResponse = JobsDeleteJobResponses[keyof JobsDeleteJobResponses];

export type JobsGetJobData = {
    body?: never;
    path: {
        /**
         * Job Id
         */
        job_id: number;
    };
    query?: never;
    url: '/job/id/{job_id}';
};

export type JobsGetJobErrors = {
    /**
     * Bad Request
     */
    400: ErrorDetail;
    /**
     * Unauthorized
     */
    401: ErrorDetail;
    /**
     * Not Found
     */
    404: ErrorDetail;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type JobsGetJobError = JobsGetJobErrors[keyof JobsGetJobErrors];

export type JobsGetJobResponses = {
    /**
     * Successful Response
     */
    200: Job;
};

export type JobsGetJobResponse = JobsGetJobResponses[keyof JobsGetJobResponses];

export type JobsGetRunningCountData = {
    body?: never;
    path: {
        job_type: JobType;
    };
    query?: never;
    url: '/job/running/{job_type}';
};

export type JobsGetRunningCountErrors = {
    /**
     * Bad Request
     */
    400: ErrorDetail;
    /**
     * Unauthorized
     */
    401: ErrorDetail;
    /**
     * Not Found
     */
    404: ErrorDetail;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type JobsGetRunningCountError = JobsGetRunningCountErrors[keyof JobsGetRunningCountErrors];

export type JobsGetRunningCountResponses = {
    /**
     * Response 200 Jobsgetrunningcount
     *
     * Successful Response
     */
    200: number;
};

export type JobsGetRunningCountResponse = JobsGetRunningCountResponses[keyof JobsGetRunningCountResponses];

export type JobsListJobsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/job';
};

export type JobsListJobsErrors = {
    /**
     * Bad Request
     */
    400: ErrorDetail;
    /**
     * Unauthorized
     */
    401: ErrorDetail;
    /**
     * Not found
     */
    404: unknown;
};

export type JobsListJobsError = JobsListJobsErrors[keyof JobsListJobsErrors];

export type JobsListJobsResponses = {
    /**
     * Successful Response
     */
    200: JobListResponse;
};

export type JobsListJobsResponse = JobsListJobsResponses[keyof JobsListJobsResponses];

export type JobsCreateJobData = {
    body: JobCreateRequest;
    path?: never;
    query?: never;
    url: '/job';
};

export type JobsCreateJobErrors = {
    /**
     * Bad Request
     */
    400: ErrorDetail;
    /**
     * Unauthorized
     */
    401: ErrorDetail;
    /**
     * Not found
     */
    404: unknown;
    /**
     * Unprocessable Entity
     */
    422: ErrorDetail;
};

export type JobsCreateJobError = JobsCreateJobErrors[keyof JobsCreateJobErrors];

export type JobsCreateJobResponses = {
    /**
     * Successful Response
     */
    200: Job;
    /**
     * Created
     */
    201: Job;
};

export type JobsCreateJobResponse = JobsCreateJobResponses[keyof JobsCreateJobResponses];

export type JobsUpdateJobData = {
    body: JobUpdateRequest;
    path?: never;
    query?: never;
    url: '/job';
};

export type JobsUpdateJobErrors = {
    /**
     * Bad Request
     */
    400: ErrorDetail;
    /**
     * Unauthorized
     */
    401: ErrorDetail;
    /**
     * Not Found
     */
    404: ErrorDetail;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type JobsUpdateJobError = JobsUpdateJobErrors[keyof JobsUpdateJobErrors];

export type JobsUpdateJobResponses = {
    /**
     * Successful Response
     */
    200: Job;
};

export type JobsUpdateJobResponse = JobsUpdateJobResponses[keyof JobsUpdateJobResponses];

export type JobsAnnotateData = {
    body: JobAnnotateRequest;
    path?: never;
    query?: never;
    url: '/job/annotate';
};

export type JobsAnnotateErrors = {
    /**
     * Bad Request
     */
    400: ErrorDetail;
    /**
     * Unauthorized
     */
    401: ErrorDetail;
    /**
     * Not Found
     */
    404: ErrorDetail;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type JobsAnnotateError = JobsAnnotateErrors[keyof JobsAnnotateErrors];

export type JobsAnnotateResponses = {
    /**
     * Successful Response
     */
    200: Job;
};

export type JobsAnnotateResponse = JobsAnnotateResponses[keyof JobsAnnotateResponses];

export type TopicsGetTopicData = {
    body?: never;
    path: {
        /**
         * Topic Id
         */
        topic_id: number;
    };
    query?: never;
    url: '/topics/id/{topic_id}';
};

export type TopicsGetTopicErrors = {
    /**
     * Bad Request
     */
    400: ErrorDetail;
    /**
     * Unauthorized
     */
    401: ErrorDetail;
    /**
     * Not Found
     */
    404: ErrorDetail;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type TopicsGetTopicError = TopicsGetTopicErrors[keyof TopicsGetTopicErrors];

export type TopicsGetTopicResponses = {
    /**
     * Successful Response
     */
    200: TopicFrontendResult;
};

export type TopicsGetTopicResponse = TopicsGetTopicResponses[keyof TopicsGetTopicResponses];

export type TopicsGetTopicGraphData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/topics/graph';
};

export type TopicsGetTopicGraphErrors = {
    /**
     * Bad Request
     */
    400: ErrorDetail;
    /**
     * Unauthorized
     */
    401: ErrorDetail;
    /**
     * Not Found
     */
    404: ErrorDetail;
};

export type TopicsGetTopicGraphError = TopicsGetTopicGraphErrors[keyof TopicsGetTopicGraphErrors];

export type TopicsGetTopicGraphResponses = {
    /**
     * Successful Response
     */
    200: TopicGraph;
};

export type TopicsGetTopicGraphResponse = TopicsGetTopicGraphResponses[keyof TopicsGetTopicGraphResponses];

export type EmbedEmbedPostData = {
    body: BodyEmbedEmbedPost;
    path?: never;
    query?: never;
    url: '/embed/';
};

export type EmbedEmbedPostErrors = {
    /**
     * Not found
     */
    404: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type EmbedEmbedPostError = EmbedEmbedPostErrors[keyof EmbedEmbedPostErrors];

export type EmbedEmbedPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type DocumentsGetAllData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Cursor
         */
        cursor?: number | null;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/doc';
};

export type DocumentsGetAllErrors = {
    /**
     * Bad Request
     */
    400: ErrorDetail;
    /**
     * Unauthorized
     */
    401: ErrorDetail;
    /**
     * Not Found
     */
    404: ErrorDetail;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DocumentsGetAllError = DocumentsGetAllErrors[keyof DocumentsGetAllErrors];

export type DocumentsGetAllResponses = {
    /**
     * Successful Response
     */
    200: DocumentListResponse;
};

export type DocumentsGetAllResponse = DocumentsGetAllResponses[keyof DocumentsGetAllResponses];

export type DocumentsGetOneData = {
    body?: never;
    path: {
        /**
         * Document Id
         */
        document_id: string;
    };
    query?: never;
    url: '/doc/doc/{document_id}';
};

export type DocumentsGetOneErrors = {
    /**
     * Bad Request
     */
    400: ErrorDetail;
    /**
     * Unauthorized
     */
    401: ErrorDetail;
    /**
     * Not Found
     */
    404: ErrorDetail;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DocumentsGetOneError = DocumentsGetOneErrors[keyof DocumentsGetOneErrors];

export type DocumentsGetOneResponses = {
    /**
     * Successful Response
     */
    200: Document;
};

export type DocumentsGetOneResponse = DocumentsGetOneResponses[keyof DocumentsGetOneResponses];

export type OntologyGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/ontology';
};

export type OntologyGetErrors = {
    /**
     * Bad Request
     */
    400: ErrorDetail;
    /**
     * Unauthorized
     */
    401: ErrorDetail;
    /**
     * Not Found
     */
    404: ErrorDetail;
};

export type OntologyGetError = OntologyGetErrors[keyof OntologyGetErrors];

export type OntologyGetResponses = {
    /**
     * Successful Response
     */
    200: OntologyFrontEnd;
};

export type OntologyGetResponse = OntologyGetResponses[keyof OntologyGetResponses];

export type AddOntologyEntryData = {
    body: OntologyEntryCreationRequest;
    path?: never;
    query?: never;
    url: '/ontology';
};

export type AddOntologyEntryErrors = {
    /**
     * Bad Request
     */
    400: ErrorDetail;
    /**
     * Unauthorized
     */
    401: ErrorDetail;
    /**
     * Not Found
     */
    404: ErrorDetail;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AddOntologyEntryError = AddOntologyEntryErrors[keyof AddOntologyEntryErrors];

export type AddOntologyEntryResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type OntologyNameExistsData = {
    body?: never;
    path: {
        /**
         * Name
         */
        name: string;
    };
    query?: never;
    url: '/ontology/exists/{name}';
};

export type OntologyNameExistsErrors = {
    /**
     * Bad Request
     */
    400: ErrorDetail;
    /**
     * Unauthorized
     */
    401: ErrorDetail;
    /**
     * Not Found
     */
    404: ErrorDetail;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type OntologyNameExistsError = OntologyNameExistsErrors[keyof OntologyNameExistsErrors];

export type OntologyNameExistsResponses = {
    /**
     * Successful Response
     */
    200: OntologyFrontEnd;
};

export type OntologyNameExistsResponse = OntologyNameExistsResponses[keyof OntologyNameExistsResponses];

export type OntologyGetAnnotationsForDocumentData = {
    body?: never;
    path: {
        /**
         * Doc Id
         */
        doc_id: string;
    };
    query?: never;
    url: '/ontology/document/{doc_id}';
};

export type OntologyGetAnnotationsForDocumentErrors = {
    /**
     * Bad Request
     */
    400: ErrorDetail;
    /**
     * Unauthorized
     */
    401: ErrorDetail;
    /**
     * Not Found
     */
    404: ErrorDetail;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type OntologyGetAnnotationsForDocumentError = OntologyGetAnnotationsForDocumentErrors[keyof OntologyGetAnnotationsForDocumentErrors];

export type OntologyGetAnnotationsForDocumentResponses = {
    /**
     * Successful Response
     */
    200: AnnotationOntologyMappingList;
};

export type OntologyGetAnnotationsForDocumentResponse = OntologyGetAnnotationsForDocumentResponses[keyof OntologyGetAnnotationsForDocumentResponses];

export type UpdateOntologyEntryData = {
    body: OntologyUpdateRequest;
    path?: never;
    query?: never;
    url: '/ontology/update';
};

export type UpdateOntologyEntryErrors = {
    /**
     * Bad Request
     */
    400: ErrorDetail;
    /**
     * Unauthorized
     */
    401: ErrorDetail;
    /**
     * Not Found
     */
    404: ErrorDetail;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateOntologyEntryError = UpdateOntologyEntryErrors[keyof UpdateOntologyEntryErrors];

export type UpdateOntologyEntryResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type DeleteOntologyEntryData = {
    body?: never;
    path: {
        /**
         * Node Id
         */
        node_id: number;
    };
    query?: never;
    url: '/ontology/node/{node_id}';
};

export type DeleteOntologyEntryErrors = {
    /**
     * Bad Request
     */
    400: ErrorDetail;
    /**
     * Unauthorized
     */
    401: ErrorDetail;
    /**
     * Not Found
     */
    404: ErrorDetail;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteOntologyEntryError = DeleteOntologyEntryErrors[keyof DeleteOntologyEntryErrors];

export type DeleteOntologyEntryResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type OntologyGetNodePathData = {
    body?: never;
    path: {
        /**
         * Path
         */
        path: string;
    };
    query?: never;
    url: '/ontology/node/{path}/path';
};

export type OntologyGetNodePathErrors = {
    /**
     * Bad Request
     */
    400: ErrorDetail;
    /**
     * Unauthorized
     */
    401: ErrorDetail;
    /**
     * Not Found
     */
    404: ErrorDetail;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type OntologyGetNodePathError = OntologyGetNodePathErrors[keyof OntologyGetNodePathErrors];

export type OntologyGetNodePathResponses = {
    /**
     * Successful Response
     */
    200: OntologyPaths;
};

export type OntologyGetNodePathResponse = OntologyGetNodePathResponses[keyof OntologyGetNodePathResponses];

export type OntologyGetPotentialMappingsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/ontology/potential_mappings';
};

export type OntologyGetPotentialMappingsErrors = {
    /**
     * Bad Request
     */
    400: ErrorDetail;
    /**
     * Unauthorized
     */
    401: ErrorDetail;
    /**
     * Not found
     */
    404: unknown;
};

export type OntologyGetPotentialMappingsError = OntologyGetPotentialMappingsErrors[keyof OntologyGetPotentialMappingsErrors];

export type OntologyGetPotentialMappingsResponses = {
    /**
     * Successful Response
     */
    200: PotentialMappingList;
};

export type OntologyGetPotentialMappingsResponse = OntologyGetPotentialMappingsResponses[keyof OntologyGetPotentialMappingsResponses];

export type MetadataCreateData = {
    body: GlobalMetadataInput;
    path?: never;
    query?: never;
    url: '/metadata/';
};

export type MetadataCreateErrors = {
    /**
     * Unauthorized
     */
    401: ErrorDetail;
    /**
     * Not Found
     */
    404: ErrorDetail;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type MetadataCreateError = MetadataCreateErrors[keyof MetadataCreateErrors];

export type MetadataCreateResponses = {
    /**
     * Successful Response
     */
    201: unknown;
};

export type MetadataGetBySourceData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/metadata';
};

export type MetadataGetBySourceErrors = {
    /**
     * Unauthorized
     */
    401: ErrorDetail;
    /**
     * Not found
     */
    404: unknown;
};

export type MetadataGetBySourceError = MetadataGetBySourceErrors[keyof MetadataGetBySourceErrors];

export type MetadataGetBySourceResponses = {
    /**
     * Successful Response
     */
    200: GlobalMetadataBySource;
};

export type MetadataGetBySourceResponse = MetadataGetBySourceResponses[keyof MetadataGetBySourceResponses];

export type MetadataProbeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/metadata/probe';
};

export type MetadataProbeErrors = {
    /**
     * Unauthorized
     */
    401: ErrorDetail;
    /**
     * Not found
     */
    404: unknown;
};

export type MetadataProbeError = MetadataProbeErrors[keyof MetadataProbeErrors];

export type MetadataProbeResponses = {
    /**
     * Successful Response
     */
    200: GlobalMetadataAvailableList;
};

export type MetadataProbeResponse = MetadataProbeResponses[keyof MetadataProbeResponses];

export type MetadataDeleteData = {
    body?: never;
    path: {
        /**
         * Metadata Id
         */
        metadata_id: string;
    };
    query?: never;
    url: '/metadata/{metadata_id}';
};

export type MetadataDeleteErrors = {
    /**
     * Unauthorized
     */
    401: ErrorDetail;
    /**
     * Not Found
     */
    404: ErrorDetail;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type MetadataDeleteError = MetadataDeleteErrors[keyof MetadataDeleteErrors];

export type MetadataDeleteResponses = {
    /**
     * Response 200 Metadatadelete
     *
     * Successful Response
     */
    200: boolean;
};

export type MetadataDeleteResponse = MetadataDeleteResponses[keyof MetadataDeleteResponses];

export type MetadataUpdateData = {
    body: GlobalMetadataUpdate;
    path?: never;
    query?: never;
    url: '/metadata/{metadata_id}';
};

export type MetadataUpdateErrors = {
    /**
     * Unauthorized
     */
    401: ErrorDetail;
    /**
     * Not Found
     */
    404: ErrorDetail;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type MetadataUpdateError = MetadataUpdateErrors[keyof MetadataUpdateErrors];

export type MetadataUpdateResponses = {
    /**
     * Response 200 Metadataupdate
     *
     * Successful Response
     */
    200: boolean;
};

export type MetadataUpdateResponse = MetadataUpdateResponses[keyof MetadataUpdateResponses];

export type PrecomputedStatsGetByNameData = {
    body?: never;
    path: {
        /**
         * Name
         */
        name: string;
    };
    query?: never;
    url: '/stats/{name}';
};

export type PrecomputedStatsGetByNameErrors = {
    /**
     * Bad Request
     */
    400: ErrorDetail;
    /**
     * Unauthorized
     */
    401: ErrorDetail;
    /**
     * Not Found
     */
    404: ErrorDetail;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PrecomputedStatsGetByNameError = PrecomputedStatsGetByNameErrors[keyof PrecomputedStatsGetByNameErrors];

export type PrecomputedStatsGetByNameResponses = {
    /**
     * Successful Response
     */
    200: PreComputedStats;
};

export type PrecomputedStatsGetByNameResponse = PrecomputedStatsGetByNameResponses[keyof PrecomputedStatsGetByNameResponses];

export type SearchHumanizeData = {
    body: SearchParams;
    path?: never;
    query?: never;
    url: '/search/humanize';
};

export type SearchHumanizeErrors = {
    /**
     * Bad Request
     */
    400: ErrorDetail;
    /**
     * Unauthorized
     */
    401: ErrorDetail;
    /**
     * Not Found
     */
    404: ErrorDetail;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SearchHumanizeError = SearchHumanizeErrors[keyof SearchHumanizeErrors];

export type SearchHumanizeResponses = {
    /**
     * Successful Response
     */
    200: HumanizedQuery;
};

export type SearchHumanizeResponse = SearchHumanizeResponses[keyof SearchHumanizeResponses];

export type SearchDocumentsData = {
    body: SearchParams;
    path?: never;
    query?: never;
    url: '/search/docs';
};

export type SearchDocumentsErrors = {
    /**
     * Bad Request
     */
    400: ErrorDetail;
    /**
     * Unauthorized
     */
    401: ErrorDetail;
    /**
     * Not Found
     */
    404: ErrorDetail;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SearchDocumentsError = SearchDocumentsErrors[keyof SearchDocumentsErrors];

export type SearchDocumentsResponses = {
    /**
     * Successful Response
     */
    200: DocumentSearchResults;
};

export type SearchDocumentsResponse = SearchDocumentsResponses[keyof SearchDocumentsResponses];

export type SearchTopicsData = {
    body: SearchParams;
    path?: never;
    query?: never;
    url: '/search/topics';
};

export type SearchTopicsErrors = {
    /**
     * Bad Request
     */
    400: ErrorDetail;
    /**
     * Unauthorized
     */
    401: ErrorDetail;
    /**
     * Not Found
     */
    404: ErrorDetail;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SearchTopicsError = SearchTopicsErrors[keyof SearchTopicsErrors];

export type SearchTopicsResponses = {
    /**
     * Successful Response
     */
    200: TopicSearchResults;
};

export type SearchTopicsResponse = SearchTopicsResponses[keyof SearchTopicsResponses];

export type SearchAnnotationsData = {
    body: SearchParams;
    path?: never;
    query?: never;
    url: '/search/annotations';
};

export type SearchAnnotationsErrors = {
    /**
     * Bad Request
     */
    400: ErrorDetail;
    /**
     * Unauthorized
     */
    401: ErrorDetail;
    /**
     * Not Found
     */
    404: ErrorDetail;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SearchAnnotationsError = SearchAnnotationsErrors[keyof SearchAnnotationsErrors];

export type SearchAnnotationsResponses = {
    /**
     * Successful Response
     */
    200: AnnotationSearchResults;
};

export type SearchAnnotationsResponse = SearchAnnotationsResponses[keyof SearchAnnotationsResponses];
