// This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod';

/**
 * AnnotationHighlight
 */
export const zAnnotationHighlight = z.object({
    id: z.string(),
    sentence_id: z.string(),
    annotation: z.string(),
    sentence: z.string()
});

/**
 * AnnotationDocResult
 */
export const zAnnotationDocResult = z.object({
    document_id: z.string(),
    document_title: z.string(),
    highlights: z.array(zAnnotationHighlight)
});

/**
 * AnnotationIdOntologyMapping
 */
export const zAnnotationIdOntologyMapping = z.object({
    annotation_id: z.string(),
    name: z.string(),
    path: z.string(),
    color: z.string()
});

/**
 * AnnotationOntologyMappingList
 */
export const zAnnotationOntologyMappingList = z.object({
    mapping: z.record(z.string(), zAnnotationIdOntologyMapping)
});

/**
 * AnnotationSearchResult
 */
export const zAnnotationSearchResult = z.object({
    name: z.string(),
    path: z.string(),
    docs: z.array(zAnnotationDocResult)
});

/**
 * AnnotationSearchResults
 */
export const zAnnotationSearchResults = z.object({
    next_cursor: z.int().nullable(),
    results: z.array(zAnnotationSearchResult),
    total: z.int()
});

/**
 * DataType
 */
export const zDataType = z.enum([
    'string',
    'string_array',
    'int',
    'float',
    'boolean',
    'date'
]);

/**
 * DocumentHighlight
 */
export const zDocumentHighlight = z.object({
    document_id: z.string(),
    sentence_id: z.string(),
    text: z.string()
});

/**
 * DocumentInfo
 */
export const zDocumentInfo = z.object({
    id: z.string(),
    title: z.string(),
    snippet: z.string()
});

/**
 * DocumentListResponse
 */
export const zDocumentListResponse = z.object({
    items: z.array(zDocumentInfo),
    total: z.int().optional().default(0),
    total_pages: z.int().optional().default(0),
    next_cursor: z.union([
        z.int(),
        z.unknown()
    ]).optional(),
    previous_cursor: z.union([
        z.int(),
        z.unknown()
    ]).optional()
});

/**
 * DocumentSearchResult
 */
export const zDocumentSearchResult = z.object({
    document_id: z.string(),
    document_title: z.string(),
    highlights: z.array(zDocumentHighlight)
});

/**
 * DocumentSearchResults
 */
export const zDocumentSearchResults = z.object({
    next_cursor: z.int().nullable(),
    results: z.array(zDocumentSearchResult),
    total: z.int()
});

/**
 * EmbeddingRequest
 */
export const zEmbeddingRequest = z.object({
    text: z.string()
});

/**
 * ErrorDetail
 */
export const zErrorDetail = z.object({
    detail: z.string(),
    code: z.int()
});

/**
 * GlobalMetadataAvailable
 */
export const zGlobalMetadataAvailable = z.object({
    source: z.string(),
    key: z.string()
});

/**
 * GlobalMetadataAvailableList
 */
export const zGlobalMetadataAvailableList = z.array(zGlobalMetadataAvailable);

/**
 * HumanizedQuery
 */
export const zHumanizedQuery = z.object({
    annotations: z.array(z.string()),
    topics: z.array(z.string())
});

/**
 * JobStatus
 */
export const zJobStatus = z.enum([
    'waiting',
    'running',
    'completed',
    'cancelled',
    'failed'
]);

/**
 * JobType
 */
export const zJobType = z.enum([
    'annotation',
    'update',
    'other'
]);

/**
 * Job
 */
export const zJob = z.object({
    id: z.int(),
    name: z.string(),
    status: zJobStatus,
    type_: zJobType,
    user_id: z.string(),
    total: z.int(),
    completed: z.int(),
    failed: z.int(),
    created_at: z.iso.datetime(),
    started_at: z.iso.datetime().nullish(),
    completed_at: z.iso.datetime().nullish(),
    api_key: z.string().nullish(),
    metadata_json: z.record(z.string(), z.unknown()).optional()
});

/**
 * JobCreateRequest
 */
export const zJobCreateRequest = z.object({
    name: z.string(),
    type_: zJobType,
    user_id: z.string().nullish(),
    total: z.int().optional(),
    api_key: z.string().nullish(),
    metadata_json: z.record(z.string(), z.unknown()).optional()
});

/**
 * JobListResponse
 */
export const zJobListResponse = z.array(zJob);

/**
 * JobUpdateRequest
 */
export const zJobUpdateRequest = z.object({
    id: z.int(),
    status: z.union([
        zJobStatus,
        z.unknown()
    ]).optional(),
    total: z.int().optional().default(0),
    completed: z.int().optional().default(0),
    failed: z.int().optional().default(0),
    metadata_json: z.union([
        z.record(z.string(), z.unknown()),
        z.unknown()
    ]).optional()
});

/**
 * MetadataSource
 */
export const zMetadataSource = z.enum([
    'document',
    'annotation',
    'sentence'
]);

/**
 * GlobalMetadata
 */
export const zGlobalMetadataInput = z.object({
    id: z.string().nullish(),
    source: zMetadataSource,
    name: z.string(),
    data_type: zDataType,
    formatter: z.string().nullish(),
    links_to_document_id: z.boolean().optional().default(false),
    links_to_metadata_id: z.string().nullish(),
    linked_to: z.union([
        z.lazy((): any => zGlobalMetadataInput),
        z.unknown()
    ]).optional()
});

/**
 * GlobalMetadata
 */
export const zGlobalMetadataOutput = z.object({
    id: z.string().nullish(),
    source: zMetadataSource,
    name: z.string(),
    data_type: zDataType,
    formatter: z.string().nullish(),
    links_to_document_id: z.boolean().optional().default(false),
    links_to_metadata_id: z.string().nullish(),
    linked_to: z.union([
        z.lazy((): any => zGlobalMetadataOutput),
        z.unknown()
    ]).optional()
});

/**
 * GlobalMetadataLinkedSource
 */
export const zGlobalMetadataLinkedSource = z.object({
    id: z.uuid(),
    source: zMetadataSource,
    name: z.string(),
    data_type: zDataType,
    formatter: z.string().nullish(),
    links_to_document_id: z.boolean().optional().default(false),
    links_to_metadata_id: z.string().nullish(),
    linked_to: z.union([
        zGlobalMetadataOutput,
        z.unknown()
    ]).optional(),
    linked_name: z.string().nullish(),
    linked_source: z.union([
        zMetadataSource,
        z.unknown()
    ]).optional()
});

/**
 * GlobalMetadataBySource
 */
export const zGlobalMetadataBySource = z.object({
    documents: z.record(z.string(), zGlobalMetadataLinkedSource),
    annotations: z.record(z.string(), zGlobalMetadataLinkedSource),
    sentences: z.record(z.string(), zGlobalMetadataLinkedSource)
});

/**
 * GlobalMetadataUpdate
 */
export const zGlobalMetadataUpdate = z.object({
    id: z.uuid(),
    source: z.union([
        zMetadataSource,
        z.unknown()
    ]).optional(),
    name: z.union([
        z.string(),
        z.unknown()
    ]).optional(),
    data_type: z.union([
        zDataType,
        z.unknown()
    ]).optional(),
    formatter: z.union([
        z.string(),
        z.unknown()
    ]).optional(),
    links_to_document_id: z.boolean().optional().default(false),
    links_to_metadata_id: z.union([
        z.uuid(),
        z.unknown()
    ]).optional()
});

/**
 * OntologyEntryCreationRequest
 */
export const zOntologyEntryCreationRequest = z.object({
    parent_id: z.int(),
    name: z.string(),
    description: z.string().nullish()
});

/**
 * OntologyMapping
 */
export const zOntologyMapping = z.object({
    id: z.int().nullish(),
    mapping: z.string()
});

/**
 * OntologyNameExists
 */
export const zOntologyNameExists = z.object({
    exists: z.boolean()
});

/**
 * OntologyPaths
 */
export const zOntologyPaths = z.array(z.string());

/**
 * OntologyProperty
 */
export const zOntologyProperty = z.object({
    value: z.union([
        z.string(),
        z.boolean(),
        z.int(),
        z.number(),
        z.array(z.string())
    ]),
    dataType: z.enum([
        'string',
        'boolean',
        'number',
        'metadata'
    ]),
    inherit: z.boolean().optional().default(false),
    display: z.boolean().optional().default(false),
    definedBy: z.string().nullish()
});

/**
 * IsolatedOntologyEntry
 */
export const zIsolatedOntologyEntry = z.object({
    id: z.int().nullish(),
    name: z.string(),
    path: z.string(),
    description: z.string(),
    color: z.string(),
    parent_id: z.int().nullish(),
    mappings: z.array(zOntologyMapping).optional(),
    properties: z.record(z.string(), zOntologyProperty).optional()
});

/**
 * OntologyFrontEnd
 */
export const zOntologyFrontEnd = z.object({
    paths: z.array(z.string()),
    nodes: z.record(z.string(), zIsolatedOntologyEntry)
});

/**
 * OntologyUpdateRequest
 */
export const zOntologyUpdateRequest = z.object({
    id: z.int(),
    color: z.union([
        z.string(),
        z.unknown()
    ]).optional(),
    description: z.union([
        z.string(),
        z.unknown()
    ]).optional(),
    properties: z.union([
        z.record(z.string(), zOntologyProperty),
        z.unknown()
    ]).optional(),
    mapping: z.union([
        z.array(z.string()),
        z.unknown()
    ]).optional()
});

/**
 * PotentialMappingList
 */
export const zPotentialMappingList = z.object({
    items: z.record(z.string(), z.union([
        z.string(),
        z.unknown()
    ]))
});

/**
 * PreComputedStats
 */
export const zPreComputedStats = z.object({
    id: z.int().nullish(),
    name: z.string(),
    value: z.record(z.string(), z.unknown()).optional()
});

/**
 * SearchParams
 */
export const zSearchParams = z.object({
    cursor: z.int().gte(1).nullish().default(1),
    limit: z.int().gte(5).optional().default(25),
    q: z.string().nullish(),
    aid: z.array(z.string()).nullish(),
    sid: z.array(z.string()).nullish(),
    tid: z.array(z.int()).nullish(),
    is_strict: z.boolean().default(false)
});

/**
 * TopicEntity
 */
export const zTopicEntity = z.object({
    entity: z.string(),
    type: z.string(),
    count: z.number()
});

/**
 * TopicHighlight
 */
export const zTopicHighlight = z.object({
    sentence_id: z.string(),
    text: z.string()
});

/**
 * TopicDocSearchResult
 */
export const zTopicDocSearchResult = z.object({
    document_id: z.string(),
    document_title: z.string(),
    highlights: z.array(zTopicHighlight)
});

/**
 * TopicNode
 */
export const zTopicNode = z.object({
    id: z.string(),
    text: z.string(),
    display: z.string(),
    value: z.number(),
    type: z.string().optional().default('topic'),
    subvalues: z.record(z.string(), z.int())
});

/**
 * TopicSearchResult
 */
export const zTopicSearchResult = z.object({
    id: z.int(),
    name: z.string(),
    docs: z.array(zTopicDocSearchResult)
});

/**
 * TopicSearchResults
 */
export const zTopicSearchResults = z.object({
    next_cursor: z.int().nullable(),
    results: z.array(zTopicSearchResult),
    total: z.int()
});

/**
 * TopicSimilarSentence
 */
export const zTopicSimilarSentence = z.object({
    sentence_id: z.string(),
    document_id: z.string(),
    similarity: z.number(),
    content: z.string()
});

/**
 * TopicFrontendResult
 */
export const zTopicFrontendResult = z.object({
    id: z.int(),
    name: z.string(),
    is_fixed: z.boolean(),
    sentence_count: z.int(),
    document_count: z.int(),
    sentences: z.array(zTopicSimilarSentence),
    entities: z.array(zTopicEntity),
    keywords: z.array(z.string())
});

/**
 * TopicSimilarity
 */
export const zTopicSimilarity = z.object({
    id1: z.string(),
    id2: z.string(),
    similarity: z.number()
});

/**
 * TopicGraph
 */
export const zTopicGraph = z.object({
    nodes: z.array(zTopicNode),
    similarities: z.array(zTopicSimilarity)
});

/**
 * ValidationError
 */
export const zValidationError = z.object({
    loc: z.array(z.union([z.string(), z.int()])),
    msg: z.string(),
    type: z.string(),
    input: z.unknown().optional(),
    ctx: z.record(z.string(), z.unknown()).optional()
});

/**
 * HTTPValidationError
 */
export const zHttpValidationError = z.object({
    detail: z.array(zValidationError).optional()
});

export const zJobsDeleteJobPath = z.object({
    job_id: z.int()
});

/**
 * Response 200 Jobsdeletejob
 *
 * Successful Response
 */
export const zJobsDeleteJobResponse = z.boolean();

export const zJobsGetJobPath = z.object({
    job_id: z.int()
});

/**
 * Successful Response
 */
export const zJobsGetJobResponse = zJob;

/**
 * Successful Response
 */
export const zJobsListJobsResponse = zJobListResponse;

export const zJobsCreateJobBody = zJobCreateRequest;

/**
 * Successful Response
 */
export const zJobsCreateJobResponse = zJob;

export const zJobsUpdateJobBody = zJobUpdateRequest;

/**
 * Successful Response
 */
export const zJobsUpdateJobResponse = zJob;

export const zTopicsGetTopicPath = z.object({
    topic_id: z.int()
});

/**
 * Successful Response
 */
export const zTopicsGetTopicResponse = zTopicFrontendResult;

/**
 * Successful Response
 */
export const zTopicsGetTopicGraphResponse = zTopicGraph;

export const zEmbedEmbedPostBody = zEmbeddingRequest;

export const zDocumentsGetAllQuery = z.object({
    cursor: z.int().gte(1).nullish().default(1),
    limit: z.int().gte(5).optional().default(25)
});

/**
 * Successful Response
 */
export const zDocumentsGetAllResponse = zDocumentListResponse;

/**
 * Successful Response
 */
export const zOntologyGetResponse = zOntologyFrontEnd;

export const zAddOntologyEntryBody = zOntologyEntryCreationRequest;

export const zOntologyNameExistsPath = z.object({
    name: z.string()
});

/**
 * Successful Response
 */
export const zOntologyNameExistsResponse = zOntologyFrontEnd;

export const zOntologyGetAnnotationsForDocumentPath = z.object({
    doc_id: z.string()
});

/**
 * Successful Response
 */
export const zOntologyGetAnnotationsForDocumentResponse = zAnnotationOntologyMappingList;

export const zUpdateOntologyEntryBody = zOntologyUpdateRequest;

export const zDeleteOntologyEntryPath = z.object({
    node_id: z.int()
});

export const zOntologyGetNodePathPath = z.object({
    path: z.string()
});

/**
 * Successful Response
 */
export const zOntologyGetNodePathResponse = zOntologyPaths;

/**
 * Successful Response
 */
export const zOntologyGetPotentialMappingsResponse = zPotentialMappingList;

export const zMetadataCreateBody = zGlobalMetadataInput;

/**
 * Successful Response
 */
export const zMetadataGetBySourceResponse = zGlobalMetadataBySource;

/**
 * Successful Response
 */
export const zMetadataProbeResponse = zGlobalMetadataAvailableList;

export const zMetadataDeletePath = z.object({
    metadata_id: z.uuid()
});

/**
 * Response 200 Metadatadelete
 *
 * Successful Response
 */
export const zMetadataDeleteResponse = z.boolean();

export const zMetadataUpdateBody = zGlobalMetadataUpdate;

/**
 * Response 200 Metadataupdate
 *
 * Successful Response
 */
export const zMetadataUpdateResponse = z.boolean();

export const zPrecomputedStatsGetByNamePath = z.object({
    name: z.string()
});

/**
 * Successful Response
 */
export const zPrecomputedStatsGetByNameResponse = zPreComputedStats;

export const zSearchHumanizeBody = zSearchParams;

/**
 * Successful Response
 */
export const zSearchHumanizeResponse = zHumanizedQuery;

export const zSearchDocumentsBody = zSearchParams;

/**
 * Successful Response
 */
export const zSearchDocumentsResponse = zDocumentSearchResults;

export const zSearchTopicsBody = zSearchParams;

/**
 * Successful Response
 */
export const zSearchTopicsResponse = zTopicSearchResults;

export const zSearchAnnotationsBody = zSearchParams;

/**
 * Successful Response
 */
export const zSearchAnnotationsResponse = zAnnotationSearchResults;
