// This file is auto-generated by @hey-api/openapi-ts

import { type InfiniteData, infiniteQueryOptions, queryOptions } from '@tanstack/react-query';

import { client } from '../client.gen';
import { ApiClient, type Options } from '../sdk.gen';
import type { AffinityScoreData, AffinityScoreError, AffinityScoreResponse, AnalysisUpdateStatsData, AnalysisUpdateStatsError, AnalysisUpdateStatsResponse, AnalyticsGetChartDataData, AnalyticsGetChartDataError, AnalyticsGetChartDataResponse, AnnotationCountsData, AnnotationCountsError, AnnotationCountsResponse, CohortInformationData, CohortInformationError, CohortInformationResponse, CohortsData, CohortsError, CohortsResponse, EntityCoOccurrenceData, EntityCoOccurrenceError, EntityCoOccurrenceResponse, EntityEventsData, EntityEventsError, EntityEventsResponse, TopicGetByIdData, TopicGetByIdError, TopicScoreData, TopicScoreError, TopicScoreResponse } from '../types.gen';

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [params];
};

export const topicGetByIdQueryKey = (options: Options<TopicGetByIdData>) => createQueryKey('topicGetById', options);

/**
 * Get Topic
 */
export const topicGetByIdOptions = (options: Options<TopicGetByIdData>) => queryOptions<unknown, TopicGetByIdError, unknown, ReturnType<typeof topicGetByIdQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await ApiClient.__registry.get().topicGetById({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: topicGetByIdQueryKey(options)
});

export const cohortInformationQueryKey = (options: Options<CohortInformationData>) => createQueryKey('cohortInformation', options);

/**
 * Cohort Information
 */
export const cohortInformationOptions = (options: Options<CohortInformationData>) => queryOptions<CohortInformationResponse, CohortInformationError, CohortInformationResponse, ReturnType<typeof cohortInformationQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await ApiClient.__registry.get().cohortInformation({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: cohortInformationQueryKey(options)
});

export const cohortsQueryKey = (options?: Options<CohortsData>) => createQueryKey('cohorts', options);

/**
 * Cohorts
 */
export const cohortsOptions = (options?: Options<CohortsData>) => queryOptions<CohortsResponse, CohortsError, CohortsResponse, ReturnType<typeof cohortsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await ApiClient.__registry.get().cohorts({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: cohortsQueryKey(options)
});

export const topicScoreQueryKey = (options: Options<TopicScoreData>) => createQueryKey('topicScore', options);

/**
 * Topic Score
 */
export const topicScoreOptions = (options: Options<TopicScoreData>) => queryOptions<TopicScoreResponse, TopicScoreError, TopicScoreResponse, ReturnType<typeof topicScoreQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await ApiClient.__registry.get().topicScore({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: topicScoreQueryKey(options)
});

export const affinityScoreQueryKey = (options: Options<AffinityScoreData>) => createQueryKey('affinityScore', options);

/**
 * Loaners
 */
export const affinityScoreOptions = (options: Options<AffinityScoreData>) => queryOptions<AffinityScoreResponse, AffinityScoreError, AffinityScoreResponse, ReturnType<typeof affinityScoreQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await ApiClient.__registry.get().affinityScore({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: affinityScoreQueryKey(options)
});

export const annotationCountsQueryKey = (options: Options<AnnotationCountsData>) => createQueryKey('annotationCounts', options);

/**
 * Counts
 */
export const annotationCountsOptions = (options: Options<AnnotationCountsData>) => queryOptions<AnnotationCountsResponse, AnnotationCountsError, AnnotationCountsResponse, ReturnType<typeof annotationCountsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await ApiClient.__registry.get().annotationCounts({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: annotationCountsQueryKey(options)
});

const createInfiniteParams = <K extends Pick<QueryKey<Options>[0], 'body' | 'headers' | 'path' | 'query'>>(queryKey: QueryKey<Options>, page: K) => {
    const params = { ...queryKey[0] };
    if (page.body) {
        params.body = {
            ...queryKey[0].body as any,
            ...page.body as any
        };
    }
    if (page.headers) {
        params.headers = {
            ...queryKey[0].headers,
            ...page.headers
        };
    }
    if (page.path) {
        params.path = {
            ...queryKey[0].path as any,
            ...page.path as any
        };
    }
    if (page.query) {
        params.query = {
            ...queryKey[0].query as any,
            ...page.query as any
        };
    }
    return params as unknown as typeof page;
};

export const annotationCountsInfiniteQueryKey = (options: Options<AnnotationCountsData>): QueryKey<Options<AnnotationCountsData>> => createQueryKey('annotationCounts', options, true);

/**
 * Counts
 */
export const annotationCountsInfiniteOptions = (options: Options<AnnotationCountsData>) => {
    const opts = infiniteQueryOptions<AnnotationCountsResponse, AnnotationCountsError, InfiniteData<AnnotationCountsResponse>, QueryKey<Options<AnnotationCountsData>>, number | Pick<QueryKey<Options<AnnotationCountsData>>[0], 'body' | 'headers' | 'path' | 'query'>>(
    // @ts-ignore
    {
        queryFn: async ({ pageParam, queryKey, signal }) => {
            // @ts-ignore
            const page: Pick<QueryKey<Options<AnnotationCountsData>>[0], 'body' | 'headers' | 'path' | 'query'> = typeof pageParam === 'object' ? pageParam : {
                body: {
                    page: pageParam
                }
            };
            const params = createInfiniteParams(queryKey, page);
            const { data } = await ApiClient.__registry.get().annotationCounts({
                ...options,
                ...params,
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: annotationCountsInfiniteQueryKey(options)
    });
    return opts as Omit<typeof opts, 'initialData'>;
};

export const entityCoOccurrenceQueryKey = (options: Options<EntityCoOccurrenceData>) => createQueryKey('entityCoOccurrence', options);

/**
 * Co Occurrence
 */
export const entityCoOccurrenceOptions = (options: Options<EntityCoOccurrenceData>) => queryOptions<EntityCoOccurrenceResponse, EntityCoOccurrenceError, EntityCoOccurrenceResponse, ReturnType<typeof entityCoOccurrenceQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await ApiClient.__registry.get().entityCoOccurrence({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: entityCoOccurrenceQueryKey(options)
});

export const analysisUpdateStatsQueryKey = (options: Options<AnalysisUpdateStatsData>) => createQueryKey('analysisUpdateStats', options);

/**
 * Update Stats
 */
export const analysisUpdateStatsOptions = (options: Options<AnalysisUpdateStatsData>) => queryOptions<AnalysisUpdateStatsResponse, AnalysisUpdateStatsError, AnalysisUpdateStatsResponse, ReturnType<typeof analysisUpdateStatsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await ApiClient.__registry.get().analysisUpdateStats({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: analysisUpdateStatsQueryKey(options)
});

export const entityEventsQueryKey = (options: Options<EntityEventsData>) => createQueryKey('entityEvents', options);

/**
 * Events
 */
export const entityEventsOptions = (options: Options<EntityEventsData>) => queryOptions<EntityEventsResponse, EntityEventsError, EntityEventsResponse, ReturnType<typeof entityEventsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await ApiClient.__registry.get().entityEvents({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: entityEventsQueryKey(options)
});

export const analyticsGetChartDataQueryKey = (options: Options<AnalyticsGetChartDataData>) => createQueryKey('analyticsGetChartData', options);

/**
 * Chart Data
 */
export const analyticsGetChartDataOptions = (options: Options<AnalyticsGetChartDataData>) => queryOptions<AnalyticsGetChartDataResponse, AnalyticsGetChartDataError, AnalyticsGetChartDataResponse, ReturnType<typeof analyticsGetChartDataQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await ApiClient.__registry.get().analyticsGetChartData({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: analyticsGetChartDataQueryKey(options)
});
