import pickle

import torch
import torch.nn as nn
from torch.utils.data import DataLoader, Dataset
from tqdm import tqdm
from transformers import AutoModel, AutoTokenizer
from lang3s import config

# --- Configuration ---
MODEL_NAME = "xlm-roberta-base"
OUTPUT_DIR = "./finetuned_xlm_roberta"
BATCH_SIZE = 32
LR = 2e-5
EPOCHS = 3
DEVICE = config.TRAINING_DEVICE


# Define a simple wrapper class
class BottleneckModel(nn.Module):
    def __init__(self, base_model, output_dim=384):
        super().__init__()
        self.backbone = base_model
        # 1. The Compression Layer (What you KEEP)
        self.compress = nn.Linear(768, output_dim)
        # 2. The Expansion Layer (Used ONLY for training)
        self.expand = nn.Linear(output_dim, 768)

    def forward(self, input_ids, attention_mask):
        outputs = self.backbone(input_ids=input_ids, attention_mask=attention_mask)

        # 1. Get 768d Embeddings (Layer 12)
        token_embeddings = outputs[0]
        input_mask_expanded = attention_mask.unsqueeze(-1).expand(token_embeddings.size()).float()
        sum_embeddings = torch.sum(token_embeddings * input_mask_expanded, 1)
        sum_mask = torch.clamp(input_mask_expanded.sum(1), min=1e-9)
        pooled_768 = sum_embeddings / sum_mask

        # 2. Compress to 368 (The useful part)
        compressed_368 = self.compress(pooled_768)

        # 3. Re-expand to 768 (To match Teacher)
        reconstructed_768 = self.expand(compressed_368)

        return reconstructed_768, compressed_368


# --- 1. Dataset Class ---
class DistillationDataset(Dataset):
    def __init__(self, data_path):
        with open(data_path, "rb") as f:
            data = pickle.load(f)
        self.texts = data["texts"]
        self.targets = data["embeddings"]

    def __len__(self):
        return len(self.texts)

    def __getitem__(self, idx):
        return self.texts[idx], self.targets[idx]


# --- 2. Custom Pooling Logic (Crucial!) ---
def student_pooling(model_output, attention_mask):
    """
    Revised: Uses ONLY the last hidden state (Layer 12) for training.
    """
    # model_output[0] is always the Last Hidden State (Layer 12)
    token_embeddings = model_output[0]

    # Standard Mean Pooling
    input_mask_expanded = attention_mask.unsqueeze(-1).expand(token_embeddings.size()).float()
    sum_embeddings = torch.sum(token_embeddings * input_mask_expanded, 1)
    sum_mask = torch.clamp(input_mask_expanded.sum(1), min=1e-9)

    # Result is pure Layer 12 output
    return sum_embeddings / sum_mask


# --- 3. Main Training Function ---
def train():
    print(f"Loading {MODEL_NAME}...")
    tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)

    # Load Model (must output hidden states for our pooling logic)
    base_model = AutoModel.from_pretrained(MODEL_NAME)
    base_model.config.output_hidden_states = True
    # --- UNFREEZING LOGIC ---
    print("Freezing backbone and unfreezing Layer 11...")
    for param in base_model.parameters():
        param.requires_grad = False

    # Unfreeze the specific last encoder layer
    # For XLM-R, it's base_model.encoder.layer[11]
    for param in base_model.encoder.layer[-1].parameters():
        param.requires_grad = True

    for param in base_model.encoder.layer[-2].parameters():
        param.requires_grad = True

    # Also unfreeze the Pooler if it exists (optional, usually skipped for mean pooling)
    if hasattr(base_model, "pooler") and base_model.pooler is not None:
        for param in base_model.pooler.parameters():
            param.requires_grad = True

    model = BottleneckModel(base_model=base_model)

    model.to(DEVICE)
    model.train()

    # Optimizer
    optimizer = torch.optim.AdamW(filter(lambda p: p.requires_grad, model.parameters()), lr=LR)
    loss_fn = nn.MSELoss()

    # Data Loaders
    dataset = DistillationDataset("train_data.pkl")  # Generated by the previous helper
    loader = DataLoader(dataset, batch_size=BATCH_SIZE, shuffle=True)

    print("Starting Training...")

    for epoch in range(EPOCHS):
        total_loss = 0
        loop = tqdm(loader, desc=f"Epoch {epoch + 1}/{EPOCHS}")

        for batch_texts, batch_targets in loop:
            optimizer.zero_grad()

            # Tokenize on the fly
            inputs = tokenizer(
                batch_texts,
                padding=True,
                truncation=True,
                max_length=128,
                return_tensors="pt"
            ).to(DEVICE)

            targets = batch_targets.to(DEVICE)

            reconstructed768, downsized = model(**inputs)
            # student_embeddings = student_pooling(outputs, inputs['attention_mask'])
            student_embeddings = torch.nn.functional.normalize(reconstructed768, p=2, dim=1)

            # Loss
            loss = loss_fn(student_embeddings, targets)

            # Backward
            loss.backward()
            optimizer.step()

            total_loss += loss.item()
            loop.set_postfix(loss=loss.item())

    # --- 4. Saving ---
    print(f"Saving fine-tuned model to {OUTPUT_DIR}...")
    model.backbone.save_pretrained(OUTPUT_DIR)
    tokenizer.save_pretrained(OUTPUT_DIR)
    torch.save(model.compress.state_dict(), f"{OUTPUT_DIR}/compressed.pt")


if __name__ == "__main__":
    train()
