# AUTOGENERATED FROM drizzle-schema.json. DO NOT EDIT BY HAND.
from __future__ import annotations

from pgvector.sqlalchemy import Vector, HALFVEC
from sqlalchemy import (Column, Integer, String, Boolean, DateTime, Text, JSON, Enum,
                        ForeignKey)
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.orm import declarative_base, relationship

Base = declarative_base()


class UserTable(Base):
    __tablename__ = 'user'

    id = Column('id', Text, primary_key=True, nullable=False)
    name = Column('name', Text, nullable=False)
    email = Column('email', Text, nullable=False, unique=True)
    emailVerified = Column('email_verified', Boolean, nullable=False)
    image = Column('image', Text, nullable=True)
    createdAt = Column('created_at', DateTime, nullable=False)
    updatedAt = Column('updated_at', DateTime, nullable=False)
    role = Column('role', Text, nullable=True)
    banned = Column('banned', Boolean, nullable=True)
    banReason = Column('ban_reason', Text, nullable=True)
    banExpires = Column('ban_expires', DateTime, nullable=True)
    username = Column('username', Text, nullable=True, unique=True)
    displayUsername = Column('display_username', Text, nullable=True)

    session_collection = relationship('SessionTable', back_populates='user', cascade='all, delete-orphan')
    account_collection = relationship('AccountTable', back_populates='user', cascade='all, delete-orphan')
    apikey_collection = relationship('ApikeyTable', back_populates='user', cascade='all, delete-orphan')
    jobs_collection = relationship('JobsTable', back_populates='user', cascade='all, delete-orphan')

    def __repr__(self) -> str:  # pragma: no cover
        return f"<%s id={self.id}>" % self.__class__.__name__


class SessionTable(Base):
    __tablename__ = 'session'

    id = Column('id', Text, primary_key=True, nullable=False)
    expiresAt = Column('expires_at', DateTime, nullable=False)
    token = Column('token', Text, nullable=False, unique=True)
    createdAt = Column('created_at', DateTime, nullable=False)
    updatedAt = Column('updated_at', DateTime, nullable=False)
    ipAddress = Column('ip_address', Text, nullable=True)
    userAgent = Column('user_agent', Text, nullable=True)
    userId = Column('user_id', Text, ForeignKey('user.id', ondelete='cascade'), nullable=False)
    impersonatedBy = Column('impersonated_by', Text, nullable=True)

    user = relationship('UserTable', back_populates='session_collection')

    def __repr__(self) -> str:  # pragma: no cover
        return f"<%s id={self.id}>" % self.__class__.__name__


class AccountTable(Base):
    __tablename__ = 'account'

    id = Column('id', Text, primary_key=True, nullable=False)
    accountId = Column('account_id', Text, nullable=False)
    providerId = Column('provider_id', Text, nullable=False)
    userId = Column('user_id', Text, ForeignKey('user.id', ondelete='cascade'), nullable=False)
    accessToken = Column('access_token', Text, nullable=True)
    refreshToken = Column('refresh_token', Text, nullable=True)
    idToken = Column('id_token', Text, nullable=True)
    accessTokenExpiresAt = Column('access_token_expires_at', DateTime, nullable=True)
    refreshTokenExpiresAt = Column('refresh_token_expires_at', DateTime, nullable=True)
    scope = Column('scope', Text, nullable=True)
    password = Column('password', Text, nullable=True)
    createdAt = Column('created_at', DateTime, nullable=False)
    updatedAt = Column('updated_at', DateTime, nullable=False)

    user = relationship('UserTable', back_populates='account_collection')

    def __repr__(self) -> str:  # pragma: no cover
        return f"<%s id={self.id}>" % self.__class__.__name__


class VerificationTable(Base):
    __tablename__ = 'verification'

    id = Column('id', Text, primary_key=True, nullable=False)
    identifier = Column('identifier', Text, nullable=False)
    value = Column('value', Text, nullable=False)
    expiresAt = Column('expires_at', DateTime, nullable=False)
    createdAt = Column('created_at', DateTime, nullable=False)
    updatedAt = Column('updated_at', DateTime, nullable=False)

    def __repr__(self) -> str:  # pragma: no cover
        return f"<%s id={self.id}>" % self.__class__.__name__


class ApikeyTable(Base):
    __tablename__ = 'apikey'

    id = Column('id', Text, primary_key=True, nullable=False)
    name = Column('name', Text, nullable=True)
    start = Column('start', Text, nullable=True)
    prefix = Column('prefix', Text, nullable=True)
    key = Column('key', Text, nullable=False)
    userId = Column('user_id', Text, ForeignKey('user.id', ondelete='cascade'), nullable=False)
    refillInterval = Column('refill_interval', Integer, nullable=True)
    refillAmount = Column('refill_amount', Integer, nullable=True)
    lastRefillAt = Column('last_refill_at', DateTime, nullable=True)
    enabled = Column('enabled', Boolean, nullable=True)
    rateLimitEnabled = Column('rate_limit_enabled', Boolean, nullable=True)
    rateLimitTimeWindow = Column('rate_limit_time_window', Integer, nullable=True)
    rateLimitMax = Column('rate_limit_max', Integer, nullable=True)
    requestCount = Column('request_count', Integer, nullable=True)
    remaining = Column('remaining', Integer, nullable=True)
    lastRequest = Column('last_request', DateTime, nullable=True)
    expiresAt = Column('expires_at', DateTime, nullable=True)
    createdAt = Column('created_at', DateTime, nullable=False)
    updatedAt = Column('updated_at', DateTime, nullable=False)
    permissions = Column('permissions', Text, nullable=True)
    metadata_ = Column('metadata', Text, nullable=True)

    user = relationship('UserTable', back_populates='apikey_collection')

    def __repr__(self) -> str:  # pragma: no cover
        return f"<%s id={self.id}>" % self.__class__.__name__


class ConfigurationTable(Base):
    __tablename__ = 'configuration'

    name = Column('name', Text, primary_key=True, nullable=False)
    value = Column('value', JSONB, nullable=False)

    def __repr__(self) -> str:  # pragma: no cover
        return f"<%s>" % self.__class__.__name__


class JobsTable(Base):
    __tablename__ = 'jobs'

    id = Column('id', Integer, primary_key=True, nullable=False)
    name = Column('name', String, nullable=False)
    apiKey = Column('apiKey', Text, nullable=True)
    userId = Column('user_id', Text, ForeignKey('user.id', ondelete='cascade'), nullable=True)
    status = Column('status', Enum('waiting', 'processing', 'complete', 'failed', name='job_status'), nullable=False)
    total = Column('total', Integer, nullable=False)
    completed = Column('completed', Integer, nullable=False)
    failed = Column('failed', Integer, nullable=False)
    metadata_ = Column('metadata', JSON, nullable=False)
    createdAt = Column('created_at', DateTime, nullable=True)
    startedAt = Column('started_at', DateTime, nullable=True)
    completedAt = Column('completed_at', DateTime, nullable=True)
    updatedAt = Column('updated_at', DateTime, nullable=True)

    user = relationship('UserTable', back_populates='jobs_collection')

    def __repr__(self) -> str:  # pragma: no cover
        return f"<%s id={self.id}>" % self.__class__.__name__


class OntologyTable(Base):
    __tablename__ = 'ontology'

    id = Column('id', Integer, primary_key=True, nullable=False)
    name = Column('name', Text, nullable=False, unique=True)
    parentId = Column('parent_id', Integer, nullable=True)
    description = Column('description', Text, nullable=True)
    color = Column('color', Text, nullable=False)
    isAttribute = Column('is_attribute', Boolean, nullable=False)
    path = Column('path', Text, nullable=False)
    properties = Column('properties', JSONB, nullable=True)

    annotation_to_ontology_collection = relationship('AnnotationToOntologyTable', back_populates='ontology',
                                                     cascade='all, delete-orphan')

    def __repr__(self) -> str:  # pragma: no cover
        return f"<%s id={self.id}>" % self.__class__.__name__


class AnnotationToOntologyTable(Base):
    __tablename__ = 'annotation_to_ontology'

    id = Column('id', Integer, primary_key=True, nullable=False)
    ontologyId = Column('ontology_id', Integer, ForeignKey('ontology.id', ondelete='cascade'), nullable=False)
    annotation = Column('annotation_type_value', Text, nullable=False)

    ontology = relationship('OntologyTable', back_populates='annotation_to_ontology_collection')

    def __repr__(self) -> str:  # pragma: no cover
        return f"<%s id={self.id}>" % self.__class__.__name__


class DocumentsTable(Base):
    __tablename__ = 'documents'

    id = Column('id', Text, primary_key=True, nullable=False)
    title = Column('title', Text, nullable=False)
    metadata_ = Column('metadata', JSONB, nullable=False)
    createdAt = Column('created_at', DateTime, nullable=True)
    updatedAt = Column('updated_at', DateTime, nullable=True)

    text_collection = relationship('TextTable', back_populates='document', cascade='all, delete-orphan')
    text_annotations_collection = relationship('TextAnnotationsTable', back_populates='document',
                                               cascade='all, delete-orphan')

    def __repr__(self) -> str:  # pragma: no cover
        return f"<%s id={self.id}>" % self.__class__.__name__


class TextTable(Base):
    __tablename__ = 'text'

    id = Column('id', Text, primary_key=True, nullable=False)
    text = Column('text', Text, nullable=False)
    fullEmbedding = Column('full_embedding', HALFVEC(), nullable=False)
    embedding = Column('embedding', Vector(), nullable=False)
    documentId = Column('doc_id', Text, ForeignKey('documents.id', ondelete='cascade'), nullable=False)
    metadata_ = Column('metadata', JSONB, nullable=False)
    createdAt = Column('created_at', DateTime, nullable=True)
    updatedAt = Column('updated_at', DateTime, nullable=True)

    document = relationship('DocumentsTable', back_populates='text_collection')
    text_annotations_collection = relationship('TextAnnotationsTable', back_populates='text_table',
                                               cascade='all, delete-orphan')

    def __repr__(self) -> str:  # pragma: no cover
        return f"<%s id={self.id}>" % self.__class__.__name__


class TextAnnotationsTable(Base):
    __tablename__ = 'text_annotations'

    id = Column('id', Text, primary_key=True, nullable=False)
    text = Column('text', Text, nullable=False)
    cleaned = Column('clean_text', Text, nullable=False)
    textId = Column('text_id', Text, ForeignKey('text.id', ondelete='cascade'), nullable=False)
    documentId = Column('doc_id', Text, ForeignKey('documents.id', ondelete='cascade'), nullable=False)
    start = Column('start', Integer, nullable=False)
    end = Column('end', Integer, nullable=False)
    sentenceId = Column('sentence_id', Integer, nullable=False)
    type_ = Column('type', Text, nullable=False)
    value = Column('value', Text, nullable=False)
    source = Column('source', Text, nullable=False)
    mapping = Column('mapping', Text, nullable=True)
    fullEmbedding = Column('full_embedding', HALFVEC(dim=768), nullable=False)
    embedding = Column('embedding', Vector(dim=768), nullable=False)
    metadata_ = Column('metadata', JSONB, nullable=False)
    createdAt = Column('created_at', DateTime, nullable=True)
    updatedAt = Column('updated_at', DateTime, nullable=True)

    text_table = relationship('TextTable', back_populates='text_annotations_collection')
    document = relationship('DocumentsTable', back_populates='text_annotations_collection')

    def __repr__(self) -> str:  # pragma: no cover
        return f"<%s id={self.id}>" % self.__class__.__name__


class TopicsTable(Base):
    __tablename__ = 'topics'

    id = Column('id', Text, primary_key=True, nullable=False)
    name = Column('name', Text, nullable=False)
    fixed = Column('is_fixed', Boolean, nullable=False)
    fullEmbedding = Column('full_embedding', Vector(), nullable=False)
    embedding = Column('embedding', Vector(), nullable=False)
    support = Column('support', Integer, nullable=False)
    createdAt = Column('created_at', DateTime, nullable=True)
    updatedAt = Column('updated_at', DateTime, nullable=True)

    def __repr__(self) -> str:  # pragma: no cover
        return f"<%s id={self.id}>" % self.__class__.__name__
