# AUTOGENERATED FROM drizzle-schema.json. DO NOT EDIT BY HAND.
from __future__ import annotations

from typing import Optional, List, Literal
from datetime import datetime, date
from pydantic import BaseModel, ConfigDict

class UserModel(BaseModel):
    model_config = ConfigDict(from_attributes=True)

    id: str
    name: str
    email: str
    emailVerified: Optional[bool] = None
    image: Optional[str] = None
    createdAt: Optional[datetime] = None
    updatedAt: Optional[datetime] = None
    role: Optional[str] = None
    banned: Optional[bool] = None
    banReason: Optional[str] = None
    banExpires: Optional[datetime] = None
    username: Optional[str] = None
    displayUsername: Optional[str] = None

class SessionModel(BaseModel):
    model_config = ConfigDict(from_attributes=True)

    id: str
    expiresAt: datetime
    token: str
    createdAt: Optional[datetime] = None
    updatedAt: datetime
    ipAddress: Optional[str] = None
    userAgent: Optional[str] = None
    userId: str
    impersonatedBy: Optional[str] = None

class AccountModel(BaseModel):
    model_config = ConfigDict(from_attributes=True)

    id: str
    accountId: str
    providerId: str
    userId: str
    accessToken: Optional[str] = None
    refreshToken: Optional[str] = None
    idToken: Optional[str] = None
    accessTokenExpiresAt: Optional[datetime] = None
    refreshTokenExpiresAt: Optional[datetime] = None
    scope: Optional[str] = None
    password: Optional[str] = None
    createdAt: Optional[datetime] = None
    updatedAt: datetime

class VerificationModel(BaseModel):
    model_config = ConfigDict(from_attributes=True)

    id: str
    identifier: str
    value: str
    expiresAt: datetime
    createdAt: Optional[datetime] = None
    updatedAt: Optional[datetime] = None

class ApikeyModel(BaseModel):
    model_config = ConfigDict(from_attributes=True)

    id: str
    name: Optional[str] = None
    start: Optional[str] = None
    prefix: Optional[str] = None
    key: str
    userId: str
    refillInterval: Optional[int] = None
    refillAmount: Optional[int] = None
    lastRefillAt: Optional[datetime] = None
    enabled: Optional[bool] = None
    rateLimitEnabled: Optional[bool] = None
    rateLimitTimeWindow: Optional[int] = None
    rateLimitMax: Optional[int] = None
    requestCount: Optional[int] = None
    remaining: Optional[int] = None
    lastRequest: Optional[datetime] = None
    expiresAt: Optional[datetime] = None
    createdAt: datetime
    updatedAt: datetime
    permissions: Optional[str] = None
    metadata: Optional[str] = None

class ConfigurationModel(BaseModel):
    model_config = ConfigDict(from_attributes=True)

    name: str
    value: dict

class JobsModel(BaseModel):
    model_config = ConfigDict(from_attributes=True)

    id: int
    name: str
    apiKey: Optional[str] = None
    userId: Optional[str] = None
    status: Optional[Literal['waiting', 'processing', 'complete', 'failed']] = None
    total: Optional[int] = None
    completed: Optional[int] = None
    failed: Optional[int] = None
    metadata: Optional[dict] = None
    createdAt: Optional[datetime] = None
    startedAt: Optional[datetime] = None
    completedAt: Optional[datetime] = None
    updatedAt: Optional[datetime] = None

class OntologyModel(BaseModel):
    model_config = ConfigDict(from_attributes=True)

    id: int
    name: str
    parentId: Optional[int] = None
    description: Optional[str] = None
    color: Optional[str] = None
    isAttribute: Optional[bool] = None
    path: str
    properties: Optional[dict] = None

class AnnotationToOntologyModel(BaseModel):
    model_config = ConfigDict(from_attributes=True)

    id: int
    ontologyId: int
    annotation: str

class DocumentsModel(BaseModel):
    model_config = ConfigDict(from_attributes=True)

    id: str
    title: str
    metadata: Optional[dict] = None
    createdAt: Optional[datetime] = None
    updatedAt: Optional[datetime] = None

class TextModel(BaseModel):
    model_config = ConfigDict(from_attributes=True)

    id: str
    text: str
    fullEmbedding: list[float]
    embedding: list[int]
    documentId: str
    metadata: Optional[dict] = None
    createdAt: Optional[datetime] = None
    updatedAt: Optional[datetime] = None

class TextAnnotationsModel(BaseModel):
    model_config = ConfigDict(from_attributes=True)

    id: str
    text: str
    cleaned: str
    textId: str
    documentId: str
    start: int
    end: int
    sentenceId: int
    type: str
    value: str
    source: str
    mapping: Optional[str] = None
    fullEmbedding: list[float]
    embedding: list[int]
    metadata: Optional[dict] = None
    createdAt: Optional[datetime] = None
    updatedAt: Optional[datetime] = None

class TopicsModel(BaseModel):
    model_config = ConfigDict(from_attributes=True)

    id: str
    name: str
    fixed: Optional[bool] = None
    fullEmbedding: list[float]
    embedding: list[int]
    support: Optional[int] = None
    createdAt: Optional[datetime] = None
    updatedAt: Optional[datetime] = None
