[project]
name = "lang3s-job-service"
version = "2025.10.3"
description = "Job Service"
authors = [{ name = "David Bracewell", email = "david@davidbracewell.com" }]
readme = "README.md"
dependencies = [
	"requests (>=2.32.5,<3.0.0)",
	"pydantic (==2.11.4)",
	"pydantic-core (==2.33.2)",
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
