from typing import Any, List, Iterable, TYPE_CHECKING
from numpy.typing import NDArray
import numpy as np

if TYPE_CHECKING:
    from .text import Text
    from .text_annotation import TextAnnotation
    from .event import Event


class TextObject:

    @property
    def id(self) -> str: ...

    @property
    def doc_id(self) -> str: ...

    @property
    def text(self) -> str: ...

    @property
    def embedding(self) -> NDArray[np.floating]: ...

    @embedding.setter
    def embedding(self, vector: NDArray[np.floating]) -> None: ...

    @property
    def tokens(self) -> List["TextAnnotation"]: ...

    @property
    def sentences(self) -> List["TextAnnotation"]: ...

    @property
    def start(self) -> int: ...

    @property
    def end(self) -> int: ...

    @property
    def is_stopword(self) -> bool: ...

    @property
    def lemma(self) -> str: ...

    @property
    def entities(self) -> List["TextAnnotation"]: ...

    @property
    def noun_chunks(self) -> List["TextAnnotation"]: ...

    @property
    def events(self) -> List[Event]: ...

    @property
    def owner(self) -> "Text": ...

    def __contains__(self, item) -> bool: ...

    def __getitem__(self, key: str) -> Any: ...

    def __setitem__(self, key: str, value: Any) -> None: ...

    def __delitem__(self, key: str) -> None: ...

    def __str__(self) -> str: ...

    def __repr__(self) -> str: ...

    def __eq__(self, other: Any) -> bool: ...

    def __hash__(self) -> int: ...

    def __iter__(self) -> Iterable["TextAnnotation"]: ...

    def get(self, metadata_key: str, default_value): ...

    def annotations_of_type(self, t: str) -> List["TextAnnotation"]: ...

    def interleave(self, annotation_type: str) -> List["TextAnnotation"]: ...

    def overlaps(self, other: "TextObject") -> bool: ...

    def to_string(self, ignore_stopwords: bool = False, lemmatize: bool = False, lowercase: bool = False) -> str: ...
